# pnpm-workspace.yaml
packages:
  - 'packages/*'
  - '!**/test/**'

catalog:
    "ethers": ^5.7.2
    "yallist": "^3.1.1"
    "@typechain/ethers-v5": ^11.1.0
    "typechain": ^8.1.0
    "@eth-optimism/sdk": "^3.1.5"
    "async-retry": "^1.3.3"
    "@types/async-retry": "^1.4.5"
    "chalk": "4.1.2"
    "dotenv": "^16.4.5"
    "gas-price-oracle": "0.5.1"
    "moment": "2.30.1"
    "node-cache": "5.1.2"
    "node-fetch": "^2.6.1"
    "ws": "^8.18.0"
    "@types/ws": "^8.5.14"
    "@derivation-tech/context": "1.0.8-appchain.3"
    "@derivation-tech/tx-plugin": "1.0.8-appchain.3"
    "@derivation-tech/contracts": "^1.0.6"
    "decimal.js": "^10.4.3"
