/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export type QuoteParamStruct = {
  minMarginAmount: BigNumberish;
  tradingFeeRatio: BigNumberish;
  protocolFeeRatio: BigNumberish;
  qtype: BigNumberish;
  tip: BigNumberish;
};

export type QuoteParamStructOutput = [
  BigNumber,
  number,
  number,
  number,
  BigNumber
] & {
  minMarginAmount: BigNumber;
  tradingFeeRatio: number;
  protocolFeeRatio: number;
  qtype: number;
  tip: BigNumber;
};

export type MarketInfoStruct = {
  mtype: string;
  market: string;
  beacon: string;
};

export type MarketInfoStructOutput = [string, string, string] & {
  mtype: string;
  market: string;
  beacon: string;
};

export interface ConfigInterface extends utils.Interface {
  functions: {
    "disableLiquidatorWhitelist()": FunctionFragment;
    "enableLpWhitelistForQuote(address,bool)": FunctionFragment;
    "getAllMarkets()": FunctionFragment;
    "getMarketInfo(string)": FunctionFragment;
    "getQuoteParam(address)": FunctionFragment;
    "initialize(address)": FunctionFragment;
    "isAuthorizedLiquidator(address)": FunctionFragment;
    "isAuthorizedLp(address,address)": FunctionFragment;
    "liquidatorWhitelist(address)": FunctionFragment;
    "lpWhitelist(address,address)": FunctionFragment;
    "markets(uint256)": FunctionFragment;
    "marketsLength()": FunctionFragment;
    "openLiquidator()": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "restrictLp(address)": FunctionFragment;
    "setLiquidatorWhitelist(address[],bool[])": FunctionFragment;
    "setLpWhiteList(address[],address[],bool[])": FunctionFragment;
    "setMarketInfo(string,address,address)": FunctionFragment;
    "setQuoteParam(address[],(uint128,uint16,uint16,uint8,uint128)[])": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "disableLiquidatorWhitelist"
      | "enableLpWhitelistForQuote"
      | "getAllMarkets"
      | "getMarketInfo"
      | "getQuoteParam"
      | "initialize"
      | "isAuthorizedLiquidator"
      | "isAuthorizedLp"
      | "liquidatorWhitelist"
      | "lpWhitelist"
      | "markets"
      | "marketsLength"
      | "openLiquidator"
      | "owner"
      | "renounceOwnership"
      | "restrictLp"
      | "setLiquidatorWhitelist"
      | "setLpWhiteList"
      | "setMarketInfo"
      | "setQuoteParam"
      | "transferOwnership"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "disableLiquidatorWhitelist",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "enableLpWhitelistForQuote",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllMarkets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketInfo",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getQuoteParam",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "initialize", values: [string]): string;
  encodeFunctionData(
    functionFragment: "isAuthorizedLiquidator",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isAuthorizedLp",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidatorWhitelist",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "lpWhitelist",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "markets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "marketsLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "openLiquidator",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "restrictLp", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setLiquidatorWhitelist",
    values: [string[], boolean[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setLpWhiteList",
    values: [string[], string[], boolean[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setMarketInfo",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setQuoteParam",
    values: [string[], QuoteParamStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "disableLiquidatorWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enableLpWhitelistForQuote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllMarkets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getQuoteParam",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorizedLiquidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorizedLp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidatorWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lpWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "markets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "marketsLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openLiquidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "restrictLp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setLiquidatorWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLpWhiteList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMarketInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setQuoteParam",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "DisableLiquidatorWhitelist()": EventFragment;
    "EnableLpWhitelistForQuote(address,bool)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "SetLiquidatorWhitelist(address,bool)": EventFragment;
    "SetLpWhitelistForQuote(address,address,bool)": EventFragment;
    "SetMarketInfo(string,address,address)": EventFragment;
    "SetQuoteParam(address,(uint128,uint16,uint16,uint8,uint128))": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DisableLiquidatorWhitelist"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EnableLpWhitelistForQuote"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetLiquidatorWhitelist"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetLpWhitelistForQuote"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetMarketInfo"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetQuoteParam"): EventFragment;
}

export interface DisableLiquidatorWhitelistEventObject {}
export type DisableLiquidatorWhitelistEvent = TypedEvent<
  [],
  DisableLiquidatorWhitelistEventObject
>;

export type DisableLiquidatorWhitelistEventFilter =
  TypedEventFilter<DisableLiquidatorWhitelistEvent>;

export interface EnableLpWhitelistForQuoteEventObject {
  quote: string;
  restricted: boolean;
}
export type EnableLpWhitelistForQuoteEvent = TypedEvent<
  [string, boolean],
  EnableLpWhitelistForQuoteEventObject
>;

export type EnableLpWhitelistForQuoteEventFilter =
  TypedEventFilter<EnableLpWhitelistForQuoteEvent>;

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface SetLiquidatorWhitelistEventObject {
  user: string;
  authorized: boolean;
}
export type SetLiquidatorWhitelistEvent = TypedEvent<
  [string, boolean],
  SetLiquidatorWhitelistEventObject
>;

export type SetLiquidatorWhitelistEventFilter =
  TypedEventFilter<SetLiquidatorWhitelistEvent>;

export interface SetLpWhitelistForQuoteEventObject {
  quote: string;
  user: string;
  authorized: boolean;
}
export type SetLpWhitelistForQuoteEvent = TypedEvent<
  [string, string, boolean],
  SetLpWhitelistForQuoteEventObject
>;

export type SetLpWhitelistForQuoteEventFilter =
  TypedEventFilter<SetLpWhitelistForQuoteEvent>;

export interface SetMarketInfoEventObject {
  mtype: string;
  market: string;
  beacon: string;
}
export type SetMarketInfoEvent = TypedEvent<
  [string, string, string],
  SetMarketInfoEventObject
>;

export type SetMarketInfoEventFilter = TypedEventFilter<SetMarketInfoEvent>;

export interface SetQuoteParamEventObject {
  quote: string;
  param: QuoteParamStructOutput;
}
export type SetQuoteParamEvent = TypedEvent<
  [string, QuoteParamStructOutput],
  SetQuoteParamEventObject
>;

export type SetQuoteParamEventFilter = TypedEventFilter<SetQuoteParamEvent>;

export interface Config extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ConfigInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    disableLiquidatorWhitelist(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    enableLpWhitelistForQuote(
      quote: string,
      enable: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getAllMarkets(overrides?: CallOverrides): Promise<[string[]]>;

    getMarketInfo(
      mtype: string,
      overrides?: CallOverrides
    ): Promise<[MarketInfoStructOutput]>;

    getQuoteParam(
      quote: string,
      overrides?: CallOverrides
    ): Promise<[QuoteParamStructOutput]>;

    initialize(
      admin: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    isAuthorizedLiquidator(
      user: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isAuthorizedLp(
      quote: string,
      user: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    liquidatorWhitelist(
      user: string,
      overrides?: CallOverrides
    ): Promise<[boolean] & { authorized: boolean }>;

    lpWhitelist(
      quote: string,
      user: string,
      overrides?: CallOverrides
    ): Promise<[boolean] & { authorized: boolean }>;

    markets(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    marketsLength(overrides?: CallOverrides): Promise<[BigNumber]>;

    openLiquidator(overrides?: CallOverrides): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    restrictLp(
      quote: string,
      overrides?: CallOverrides
    ): Promise<[boolean] & { restricted: boolean }>;

    setLiquidatorWhitelist(
      users: string[],
      flags: boolean[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setLpWhiteList(
      quotes: string[],
      users: string[],
      flags: boolean[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setMarketInfo(
      mtype: string,
      market: string,
      beacon: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setQuoteParam(
      coins: string[],
      params: QuoteParamStruct[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  disableLiquidatorWhitelist(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  enableLpWhitelistForQuote(
    quote: string,
    enable: boolean,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getAllMarkets(overrides?: CallOverrides): Promise<string[]>;

  getMarketInfo(
    mtype: string,
    overrides?: CallOverrides
  ): Promise<MarketInfoStructOutput>;

  getQuoteParam(
    quote: string,
    overrides?: CallOverrides
  ): Promise<QuoteParamStructOutput>;

  initialize(
    admin: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  isAuthorizedLiquidator(
    user: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isAuthorizedLp(
    quote: string,
    user: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  liquidatorWhitelist(
    user: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  lpWhitelist(
    quote: string,
    user: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  markets(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  marketsLength(overrides?: CallOverrides): Promise<BigNumber>;

  openLiquidator(overrides?: CallOverrides): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  restrictLp(quote: string, overrides?: CallOverrides): Promise<boolean>;

  setLiquidatorWhitelist(
    users: string[],
    flags: boolean[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setLpWhiteList(
    quotes: string[],
    users: string[],
    flags: boolean[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setMarketInfo(
    mtype: string,
    market: string,
    beacon: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setQuoteParam(
    coins: string[],
    params: QuoteParamStruct[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    disableLiquidatorWhitelist(overrides?: CallOverrides): Promise<void>;

    enableLpWhitelistForQuote(
      quote: string,
      enable: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    getAllMarkets(overrides?: CallOverrides): Promise<string[]>;

    getMarketInfo(
      mtype: string,
      overrides?: CallOverrides
    ): Promise<MarketInfoStructOutput>;

    getQuoteParam(
      quote: string,
      overrides?: CallOverrides
    ): Promise<QuoteParamStructOutput>;

    initialize(admin: string, overrides?: CallOverrides): Promise<void>;

    isAuthorizedLiquidator(
      user: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isAuthorizedLp(
      quote: string,
      user: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    liquidatorWhitelist(
      user: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    lpWhitelist(
      quote: string,
      user: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    markets(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    marketsLength(overrides?: CallOverrides): Promise<BigNumber>;

    openLiquidator(overrides?: CallOverrides): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    restrictLp(quote: string, overrides?: CallOverrides): Promise<boolean>;

    setLiquidatorWhitelist(
      users: string[],
      flags: boolean[],
      overrides?: CallOverrides
    ): Promise<void>;

    setLpWhiteList(
      quotes: string[],
      users: string[],
      flags: boolean[],
      overrides?: CallOverrides
    ): Promise<void>;

    setMarketInfo(
      mtype: string,
      market: string,
      beacon: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setQuoteParam(
      coins: string[],
      params: QuoteParamStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "DisableLiquidatorWhitelist()"(): DisableLiquidatorWhitelistEventFilter;
    DisableLiquidatorWhitelist(): DisableLiquidatorWhitelistEventFilter;

    "EnableLpWhitelistForQuote(address,bool)"(
      quote?: null,
      restricted?: null
    ): EnableLpWhitelistForQuoteEventFilter;
    EnableLpWhitelistForQuote(
      quote?: null,
      restricted?: null
    ): EnableLpWhitelistForQuoteEventFilter;

    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;

    "SetLiquidatorWhitelist(address,bool)"(
      user?: null,
      authorized?: null
    ): SetLiquidatorWhitelistEventFilter;
    SetLiquidatorWhitelist(
      user?: null,
      authorized?: null
    ): SetLiquidatorWhitelistEventFilter;

    "SetLpWhitelistForQuote(address,address,bool)"(
      quote?: null,
      user?: null,
      authorized?: null
    ): SetLpWhitelistForQuoteEventFilter;
    SetLpWhitelistForQuote(
      quote?: null,
      user?: null,
      authorized?: null
    ): SetLpWhitelistForQuoteEventFilter;

    "SetMarketInfo(string,address,address)"(
      mtype?: null,
      market?: null,
      beacon?: null
    ): SetMarketInfoEventFilter;
    SetMarketInfo(
      mtype?: null,
      market?: null,
      beacon?: null
    ): SetMarketInfoEventFilter;

    "SetQuoteParam(address,(uint128,uint16,uint16,uint8,uint128))"(
      quote?: null,
      param?: null
    ): SetQuoteParamEventFilter;
    SetQuoteParam(quote?: null, param?: null): SetQuoteParamEventFilter;
  };

  estimateGas: {
    disableLiquidatorWhitelist(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    enableLpWhitelistForQuote(
      quote: string,
      enable: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    getAllMarkets(overrides?: CallOverrides): Promise<BigNumber>;

    getMarketInfo(mtype: string, overrides?: CallOverrides): Promise<BigNumber>;

    getQuoteParam(quote: string, overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      admin: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    isAuthorizedLiquidator(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isAuthorizedLp(
      quote: string,
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    liquidatorWhitelist(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lpWhitelist(
      quote: string,
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    markets(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    marketsLength(overrides?: CallOverrides): Promise<BigNumber>;

    openLiquidator(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    restrictLp(quote: string, overrides?: CallOverrides): Promise<BigNumber>;

    setLiquidatorWhitelist(
      users: string[],
      flags: boolean[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setLpWhiteList(
      quotes: string[],
      users: string[],
      flags: boolean[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setMarketInfo(
      mtype: string,
      market: string,
      beacon: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setQuoteParam(
      coins: string[],
      params: QuoteParamStruct[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    disableLiquidatorWhitelist(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    enableLpWhitelistForQuote(
      quote: string,
      enable: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getAllMarkets(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getMarketInfo(
      mtype: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getQuoteParam(
      quote: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      admin: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    isAuthorizedLiquidator(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isAuthorizedLp(
      quote: string,
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    liquidatorWhitelist(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lpWhitelist(
      quote: string,
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    markets(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    marketsLength(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    openLiquidator(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    restrictLp(
      quote: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setLiquidatorWhitelist(
      users: string[],
      flags: boolean[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setLpWhiteList(
      quotes: string[],
      users: string[],
      flags: boolean[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setMarketInfo(
      mtype: string,
      market: string,
      beacon: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setQuoteParam(
      coins: string[],
      params: QuoteParamStruct[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
