/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export type RangeStruct = {
  liquidity: BigNumberish;
  entryFeeIndex: BigNumberish;
  balance: BigNumberish;
  sqrtEntryPX96: BigNumberish;
};

export type RangeStructOutput = [BigNumber, BigNumber, BigNumber, BigNumber] & {
  liquidity: BigNumber;
  entryFeeIndex: BigNumber;
  balance: BigNumber;
  sqrtEntryPX96: BigNumber;
};

export type OrderStruct = { balance: BigNumberish; size: BigNumberish };

export type OrderStructOutput = [BigNumber, BigNumber] & {
  balance: BigNumber;
  size: BigNumber;
};

export type PositionCacheStruct = {
  balance: BigNumberish;
  size: BigNumberish;
  entryNotional: BigNumberish;
  entrySocialLossIndex: BigNumberish;
  entryFundingIndex: BigNumberish;
};

export type PositionCacheStructOutput = [
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber
] & {
  balance: BigNumber;
  size: BigNumber;
  entryNotional: BigNumber;
  entrySocialLossIndex: BigNumber;
  entryFundingIndex: BigNumber;
};

export type QuotationStruct = {
  benchmark: BigNumberish;
  sqrtFairPX96: BigNumberish;
  tick: BigNumberish;
  mark: BigNumberish;
  entryNotional: BigNumberish;
  fee: BigNumberish;
  minAmount: BigNumberish;
  sqrtPostFairPX96: BigNumberish;
  postTick: BigNumberish;
};

export type QuotationStructOutput = [
  BigNumber,
  BigNumber,
  number,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  number
] & {
  benchmark: BigNumber;
  sqrtFairPX96: BigNumber;
  tick: number;
  mark: BigNumber;
  entryNotional: BigNumber;
  fee: BigNumber;
  minAmount: BigNumber;
  sqrtPostFairPX96: BigNumber;
  postTick: number;
};

export type QuoteParamStruct = {
  minMarginAmount: BigNumberish;
  tradingFeeRatio: BigNumberish;
  protocolFeeRatio: BigNumberish;
  qtype: BigNumberish;
  tip: BigNumberish;
};

export type QuoteParamStructOutput = [
  BigNumber,
  number,
  number,
  number,
  BigNumber
] & {
  minMarginAmount: BigNumber;
  tradingFeeRatio: number;
  protocolFeeRatio: number;
  qtype: number;
  tip: BigNumber;
};

export interface InstrumentInterface extends utils.Interface {
  functions: {
    "add(bytes32[2])": FunctionFragment;
    "addFor(address,bytes32[2])": FunctionFragment;
    "batchPlace(bytes32[3])": FunctionFragment;
    "batchPlaceFor(address,bytes32[3])": FunctionFragment;
    "cancel(bytes32)": FunctionFragment;
    "cancelFor(address,bytes32)": FunctionFragment;
    "claimProtocolFee(uint32)": FunctionFragment;
    "condition()": FunctionFragment;
    "donateInsuranceFund(uint32,uint256)": FunctionFragment;
    "fill(bytes32)": FunctionFragment;
    "freeze()": FunctionFragment;
    "getExpiries()": FunctionFragment;
    "handler()": FunctionFragment;
    "init(address,bytes32[2])": FunctionFragment;
    "initialize(bytes)": FunctionFragment;
    "inquire(uint32,int256)": FunctionFragment;
    "liquidate(uint32,address,int256,uint256)": FunctionFragment;
    "multicall(bytes[])": FunctionFragment;
    "normalize()": FunctionFragment;
    "place(bytes32[2])": FunctionFragment;
    "placeFor(address,bytes32[2])": FunctionFragment;
    "queryAccount(uint32,address,uint8,bytes)": FunctionFragment;
    "queryContext(uint32,uint8,uint256[],bytes)": FunctionFragment;
    "querySetting(uint256[])": FunctionFragment;
    "recycleInsuranceFund(uint32)": FunctionFragment;
    "remove(bytes32[2])": FunctionFragment;
    "removeFor(bytes32[2])": FunctionFragment;
    "resolve(uint128)": FunctionFragment;
    "setDisableOrderRebate(bool)": FunctionFragment;
    "setFundingHour(uint8)": FunctionFragment;
    "setLeverage(uint16,uint16)": FunctionFragment;
    "setPlacePaused(bool)": FunctionFragment;
    "setQuoteParam((uint128,uint16,uint16,uint8,uint128))": FunctionFragment;
    "settle(uint32,address)": FunctionFragment;
    "sweep(uint32,address,int256)": FunctionFragment;
    "trade(bytes32[2])": FunctionFragment;
    "tradeFor(address,bytes32[2])": FunctionFragment;
    "update(uint32)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "add"
      | "addFor"
      | "batchPlace"
      | "batchPlaceFor"
      | "cancel"
      | "cancelFor"
      | "claimProtocolFee"
      | "condition"
      | "donateInsuranceFund"
      | "fill"
      | "freeze"
      | "getExpiries"
      | "handler"
      | "init"
      | "initialize"
      | "inquire"
      | "liquidate"
      | "multicall"
      | "normalize"
      | "place"
      | "placeFor"
      | "queryAccount"
      | "queryContext"
      | "querySetting"
      | "recycleInsuranceFund"
      | "remove"
      | "removeFor"
      | "resolve"
      | "setDisableOrderRebate"
      | "setFundingHour"
      | "setLeverage"
      | "setPlacePaused"
      | "setQuoteParam"
      | "settle"
      | "sweep"
      | "trade"
      | "tradeFor"
      | "update"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "add",
    values: [[BytesLike, BytesLike]]
  ): string;
  encodeFunctionData(
    functionFragment: "addFor",
    values: [string, [BytesLike, BytesLike]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchPlace",
    values: [[BytesLike, BytesLike, BytesLike]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchPlaceFor",
    values: [string, [BytesLike, BytesLike, BytesLike]]
  ): string;
  encodeFunctionData(functionFragment: "cancel", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "cancelFor",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimProtocolFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "condition", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "donateInsuranceFund",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "fill", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "freeze", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getExpiries",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "handler", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "init",
    values: [string, [BytesLike, BytesLike]]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "inquire",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidate",
    values: [BigNumberish, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "multicall",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(functionFragment: "normalize", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "place",
    values: [[BytesLike, BytesLike]]
  ): string;
  encodeFunctionData(
    functionFragment: "placeFor",
    values: [string, [BytesLike, BytesLike]]
  ): string;
  encodeFunctionData(
    functionFragment: "queryAccount",
    values: [BigNumberish, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "queryContext",
    values: [BigNumberish, BigNumberish, BigNumberish[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "querySetting",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "recycleInsuranceFund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "remove",
    values: [[BytesLike, BytesLike]]
  ): string;
  encodeFunctionData(
    functionFragment: "removeFor",
    values: [[BytesLike, BytesLike]]
  ): string;
  encodeFunctionData(
    functionFragment: "resolve",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDisableOrderRebate",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setFundingHour",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setLeverage",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlacePaused",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setQuoteParam",
    values: [QuoteParamStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "settle",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "sweep",
    values: [BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "trade",
    values: [[BytesLike, BytesLike]]
  ): string;
  encodeFunctionData(
    functionFragment: "tradeFor",
    values: [string, [BytesLike, BytesLike]]
  ): string;
  encodeFunctionData(
    functionFragment: "update",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "add", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addFor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "batchPlace", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchPlaceFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancel", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancelFor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimProtocolFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "condition", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "donateInsuranceFund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fill", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "freeze", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getExpiries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "handler", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "init", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "inquire", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "liquidate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "multicall", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "normalize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "place", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "placeFor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "queryAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "queryContext",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "querySetting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recycleInsuranceFund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "remove", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "removeFor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "resolve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setDisableOrderRebate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFundingHour",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLeverage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlacePaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setQuoteParam",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "settle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sweep", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "trade", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tradeFor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "update", data: BytesLike): Result;

  events: {
    "Add(uint32,address,int24,int24,(uint128,uint128,uint96,uint160))": EventFragment;
    "Adjust(uint32,address,int256)": EventFragment;
    "Cancel(uint32,address,int24,uint32,uint256,(int256,int256,uint256,uint256,int256))": EventFragment;
    "ClaimProtocolFee(uint32,uint256)": EventFragment;
    "DeleteContext(uint32)": EventFragment;
    "DonateInsuranceFund(uint32,address,uint256)": EventFragment;
    "Fill(uint32,address,int24,uint32,uint256,(int256,int256,uint256,uint256,int256),address,uint256)": EventFragment;
    "FundingFee(address,int256)": EventFragment;
    "Liquidate(uint32,address,uint256,uint256,address,int256)": EventFragment;
    "Place(uint32,address,int24,uint32,(uint128,int128))": EventFragment;
    "RecycleInsuranceFund(uint32,uint256)": EventFragment;
    "Remove(uint32,address,int24,int24,uint256,(int256,int256,uint256,uint256,int256),address,uint256)": EventFragment;
    "Settle(uint32,address,uint256,uint256,address)": EventFragment;
    "Sweep(uint32,address,int256,int256,uint256,uint256,uint16,uint160,uint256,address)": EventFragment;
    "Trade(uint32,address,int256,uint256,int256,uint256,uint256,uint16,uint160,uint256)": EventFragment;
    "UpdateAmmStatus(uint32,uint8,uint160,uint256)": EventFragment;
    "UpdateCondition(uint32,uint8)": EventFragment;
    "UpdateFeeState(uint32,uint128,uint128)": EventFragment;
    "UpdateFundingHour(uint8)": EventFragment;
    "UpdateFundingIndex(uint256)": EventFragment;
    "UpdateMarginRatio(uint16,uint16)": EventFragment;
    "UpdateParam((uint128,uint16,uint16,uint8,uint128))": EventFragment;
    "UpdatePosition(uint32,address,(int256,int256,uint256,uint256,int256))": EventFragment;
    "UpdateSocialLossInsuranceFund(uint32,uint128,uint128,uint128)": EventFragment;
    "AdminChanged(address,address)": EventFragment;
    "BeaconUpgraded(address)": EventFragment;
    "Upgraded(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Add"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Adjust"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Cancel"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ClaimProtocolFee"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DeleteContext"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DonateInsuranceFund"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Fill"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FundingFee"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Liquidate"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Place"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RecycleInsuranceFund"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Remove"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Settle"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Sweep"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Trade"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdateAmmStatus"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdateCondition"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdateFeeState"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdateFundingHour"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdateFundingIndex"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdateMarginRatio"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdateParam"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdatePosition"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "UpdateSocialLossInsuranceFund"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BeaconUpgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Upgraded"): EventFragment;
}

export interface AddEventObject {
  expiry: number;
  trader: string;
  tickLower: number;
  tickUpper: number;
  range: RangeStructOutput;
}
export type AddEvent = TypedEvent<
  [number, string, number, number, RangeStructOutput],
  AddEventObject
>;

export type AddEventFilter = TypedEventFilter<AddEvent>;

export interface AdjustEventObject {
  expiry: number;
  trader: string;
  net: BigNumber;
}
export type AdjustEvent = TypedEvent<
  [number, string, BigNumber],
  AdjustEventObject
>;

export type AdjustEventFilter = TypedEventFilter<AdjustEvent>;

export interface CancelEventObject {
  expiry: number;
  trader: string;
  tick: number;
  nonce: number;
  fee: BigNumber;
  pic: PositionCacheStructOutput;
}
export type CancelEvent = TypedEvent<
  [number, string, number, number, BigNumber, PositionCacheStructOutput],
  CancelEventObject
>;

export type CancelEventFilter = TypedEventFilter<CancelEvent>;

export interface ClaimProtocolFeeEventObject {
  expiry: number;
  amount: BigNumber;
}
export type ClaimProtocolFeeEvent = TypedEvent<
  [number, BigNumber],
  ClaimProtocolFeeEventObject
>;

export type ClaimProtocolFeeEventFilter =
  TypedEventFilter<ClaimProtocolFeeEvent>;

export interface DeleteContextEventObject {
  expiry: number;
}
export type DeleteContextEvent = TypedEvent<[number], DeleteContextEventObject>;

export type DeleteContextEventFilter = TypedEventFilter<DeleteContextEvent>;

export interface DonateInsuranceFundEventObject {
  expiry: number;
  donator: string;
  amount: BigNumber;
}
export type DonateInsuranceFundEvent = TypedEvent<
  [number, string, BigNumber],
  DonateInsuranceFundEventObject
>;

export type DonateInsuranceFundEventFilter =
  TypedEventFilter<DonateInsuranceFundEvent>;

export interface FillEventObject {
  expiry: number;
  trader: string;
  tick: number;
  nonce: number;
  fee: BigNumber;
  pic: PositionCacheStructOutput;
  operator: string;
  tip: BigNumber;
}
export type FillEvent = TypedEvent<
  [
    number,
    string,
    number,
    number,
    BigNumber,
    PositionCacheStructOutput,
    string,
    BigNumber
  ],
  FillEventObject
>;

export type FillEventFilter = TypedEventFilter<FillEvent>;

export interface FundingFeeEventObject {
  trader: string;
  funding: BigNumber;
}
export type FundingFeeEvent = TypedEvent<
  [string, BigNumber],
  FundingFeeEventObject
>;

export type FundingFeeEventFilter = TypedEventFilter<FundingFeeEvent>;

export interface LiquidateEventObject {
  expiry: number;
  trader: string;
  amount: BigNumber;
  mark: BigNumber;
  target: string;
  size: BigNumber;
}
export type LiquidateEvent = TypedEvent<
  [number, string, BigNumber, BigNumber, string, BigNumber],
  LiquidateEventObject
>;

export type LiquidateEventFilter = TypedEventFilter<LiquidateEvent>;

export interface PlaceEventObject {
  expiry: number;
  trader: string;
  tick: number;
  nonce: number;
  order: OrderStructOutput;
}
export type PlaceEvent = TypedEvent<
  [number, string, number, number, OrderStructOutput],
  PlaceEventObject
>;

export type PlaceEventFilter = TypedEventFilter<PlaceEvent>;

export interface RecycleInsuranceFundEventObject {
  expiry: number;
  amount: BigNumber;
}
export type RecycleInsuranceFundEvent = TypedEvent<
  [number, BigNumber],
  RecycleInsuranceFundEventObject
>;

export type RecycleInsuranceFundEventFilter =
  TypedEventFilter<RecycleInsuranceFundEvent>;

export interface RemoveEventObject {
  expiry: number;
  trader: string;
  tickLower: number;
  tickUpper: number;
  fee: BigNumber;
  pic: PositionCacheStructOutput;
  operator: string;
  tip: BigNumber;
}
export type RemoveEvent = TypedEvent<
  [
    number,
    string,
    number,
    number,
    BigNumber,
    PositionCacheStructOutput,
    string,
    BigNumber
  ],
  RemoveEventObject
>;

export type RemoveEventFilter = TypedEventFilter<RemoveEvent>;

export interface SettleEventObject {
  expiry: number;
  trader: string;
  settlement: BigNumber;
  balance: BigNumber;
  operator: string;
}
export type SettleEvent = TypedEvent<
  [number, string, BigNumber, BigNumber, string],
  SettleEventObject
>;

export type SettleEventFilter = TypedEventFilter<SettleEvent>;

export interface SweepEventObject {
  expiry: number;
  trader: string;
  size: BigNumber;
  takenSize: BigNumber;
  takenValue: BigNumber;
  entryNotional: BigNumber;
  feeRatio: number;
  sqrtPX96: BigNumber;
  mark: BigNumber;
  operator: string;
}
export type SweepEvent = TypedEvent<
  [
    number,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    number,
    BigNumber,
    BigNumber,
    string
  ],
  SweepEventObject
>;

export type SweepEventFilter = TypedEventFilter<SweepEvent>;

export interface TradeEventObject {
  expiry: number;
  trader: string;
  size: BigNumber;
  amount: BigNumber;
  takenSize: BigNumber;
  takenValue: BigNumber;
  entryNotional: BigNumber;
  feeRatio: number;
  sqrtPX96: BigNumber;
  mark: BigNumber;
}
export type TradeEvent = TypedEvent<
  [
    number,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    number,
    BigNumber,
    BigNumber
  ],
  TradeEventObject
>;

export type TradeEventFilter = TypedEventFilter<TradeEvent>;

export interface UpdateAmmStatusEventObject {
  expiry: number;
  status: number;
  sqrtPX96: BigNumber;
  mark: BigNumber;
}
export type UpdateAmmStatusEvent = TypedEvent<
  [number, number, BigNumber, BigNumber],
  UpdateAmmStatusEventObject
>;

export type UpdateAmmStatusEventFilter = TypedEventFilter<UpdateAmmStatusEvent>;

export interface UpdateConditionEventObject {
  timestamp: number;
  condition: number;
}
export type UpdateConditionEvent = TypedEvent<
  [number, number],
  UpdateConditionEventObject
>;

export type UpdateConditionEventFilter = TypedEventFilter<UpdateConditionEvent>;

export interface UpdateFeeStateEventObject {
  expiry: number;
  feeIndex: BigNumber;
  protocolFee: BigNumber;
}
export type UpdateFeeStateEvent = TypedEvent<
  [number, BigNumber, BigNumber],
  UpdateFeeStateEventObject
>;

export type UpdateFeeStateEventFilter = TypedEventFilter<UpdateFeeStateEvent>;

export interface UpdateFundingHourEventObject {
  fundingHour: number;
}
export type UpdateFundingHourEvent = TypedEvent<
  [number],
  UpdateFundingHourEventObject
>;

export type UpdateFundingHourEventFilter =
  TypedEventFilter<UpdateFundingHourEvent>;

export interface UpdateFundingIndexEventObject {
  fundingIndex: BigNumber;
}
export type UpdateFundingIndexEvent = TypedEvent<
  [BigNumber],
  UpdateFundingIndexEventObject
>;

export type UpdateFundingIndexEventFilter =
  TypedEventFilter<UpdateFundingIndexEvent>;

export interface UpdateMarginRatioEventObject {
  initialMarginRatio: number;
  maintenanceMarginRatio: number;
}
export type UpdateMarginRatioEvent = TypedEvent<
  [number, number],
  UpdateMarginRatioEventObject
>;

export type UpdateMarginRatioEventFilter =
  TypedEventFilter<UpdateMarginRatioEvent>;

export interface UpdateParamEventObject {
  param: QuoteParamStructOutput;
}
export type UpdateParamEvent = TypedEvent<
  [QuoteParamStructOutput],
  UpdateParamEventObject
>;

export type UpdateParamEventFilter = TypedEventFilter<UpdateParamEvent>;

export interface UpdatePositionEventObject {
  expiry: number;
  trader: string;
  pic: PositionCacheStructOutput;
}
export type UpdatePositionEvent = TypedEvent<
  [number, string, PositionCacheStructOutput],
  UpdatePositionEventObject
>;

export type UpdatePositionEventFilter = TypedEventFilter<UpdatePositionEvent>;

export interface UpdateSocialLossInsuranceFundEventObject {
  expiry: number;
  longSocialLossIndex: BigNumber;
  shortSocialLossIndex: BigNumber;
  insuranceFund: BigNumber;
}
export type UpdateSocialLossInsuranceFundEvent = TypedEvent<
  [number, BigNumber, BigNumber, BigNumber],
  UpdateSocialLossInsuranceFundEventObject
>;

export type UpdateSocialLossInsuranceFundEventFilter =
  TypedEventFilter<UpdateSocialLossInsuranceFundEvent>;

export interface AdminChangedEventObject {
  previousAdmin: string;
  newAdmin: string;
}
export type AdminChangedEvent = TypedEvent<
  [string, string],
  AdminChangedEventObject
>;

export type AdminChangedEventFilter = TypedEventFilter<AdminChangedEvent>;

export interface BeaconUpgradedEventObject {
  beacon: string;
}
export type BeaconUpgradedEvent = TypedEvent<
  [string],
  BeaconUpgradedEventObject
>;

export type BeaconUpgradedEventFilter = TypedEventFilter<BeaconUpgradedEvent>;

export interface UpgradedEventObject {
  implementation: string;
}
export type UpgradedEvent = TypedEvent<[string], UpgradedEventObject>;

export type UpgradedEventFilter = TypedEventFilter<UpgradedEvent>;

export interface Instrument extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: InstrumentInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    add(
      args: [BytesLike, BytesLike],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    addFor(
      to: string,
      args: [BytesLike, BytesLike],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    batchPlace(
      args: [BytesLike, BytesLike, BytesLike],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    batchPlaceFor(
      to: string,
      args: [BytesLike, BytesLike, BytesLike],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    cancel(
      arg: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    cancelFor(
      to: string,
      arg: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    claimProtocolFee(
      expiry: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    condition(overrides?: CallOverrides): Promise<[number]>;

    donateInsuranceFund(
      expiry: BigNumberish,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    fill(
      arg: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    freeze(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getExpiries(overrides?: CallOverrides): Promise<[number[]]>;

    handler(overrides?: CallOverrides): Promise<[string]>;

    init(
      target: string,
      args: [BytesLike, BytesLike],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    initialize(
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    inquire(
      expiry: BigNumberish,
      size: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[QuotationStructOutput]>;

    liquidate(
      expiry: BigNumberish,
      target: string,
      size: BigNumberish,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    multicall(
      data: BytesLike[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    normalize(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    place(
      args: [BytesLike, BytesLike],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    placeFor(
      to: string,
      args: [BytesLike, BytesLike],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    queryAccount(
      expiry: BigNumberish,
      target: string,
      query: BigNumberish,
      inputs: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string] & { result: string }>;

    queryContext(
      expiry: BigNumberish,
      query: BigNumberish,
      offsets: BigNumberish[],
      inputs: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    querySetting(
      offsets: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    recycleInsuranceFund(
      expiry: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    remove(
      args: [BytesLike, BytesLike],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    removeFor(
      args: [BytesLike, BytesLike],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    resolve(
      settlementPrice: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setDisableOrderRebate(
      disable: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setFundingHour(
      newFundingHour: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setLeverage(
      initialMarginRatio: BigNumberish,
      maintenanceMarginRatio: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setPlacePaused(
      paused: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setQuoteParam(
      param: QuoteParamStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    settle(
      expiry: BigNumberish,
      target: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    sweep(
      expiry: BigNumberish,
      target: string,
      size: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    trade(
      args: [BytesLike, BytesLike],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    tradeFor(
      to: string,
      args: [BytesLike, BytesLike],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    update(
      expiry: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  add(
    args: [BytesLike, BytesLike],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  addFor(
    to: string,
    args: [BytesLike, BytesLike],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  batchPlace(
    args: [BytesLike, BytesLike, BytesLike],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  batchPlaceFor(
    to: string,
    args: [BytesLike, BytesLike, BytesLike],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  cancel(
    arg: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  cancelFor(
    to: string,
    arg: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  claimProtocolFee(
    expiry: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  condition(overrides?: CallOverrides): Promise<number>;

  donateInsuranceFund(
    expiry: BigNumberish,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  fill(
    arg: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  freeze(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getExpiries(overrides?: CallOverrides): Promise<number[]>;

  handler(overrides?: CallOverrides): Promise<string>;

  init(
    target: string,
    args: [BytesLike, BytesLike],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  initialize(
    data: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  inquire(
    expiry: BigNumberish,
    size: BigNumberish,
    overrides?: CallOverrides
  ): Promise<QuotationStructOutput>;

  liquidate(
    expiry: BigNumberish,
    target: string,
    size: BigNumberish,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  multicall(
    data: BytesLike[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  normalize(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  place(
    args: [BytesLike, BytesLike],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  placeFor(
    to: string,
    args: [BytesLike, BytesLike],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  queryAccount(
    expiry: BigNumberish,
    target: string,
    query: BigNumberish,
    inputs: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  queryContext(
    expiry: BigNumberish,
    query: BigNumberish,
    offsets: BigNumberish[],
    inputs: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  querySetting(
    offsets: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  recycleInsuranceFund(
    expiry: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  remove(
    args: [BytesLike, BytesLike],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  removeFor(
    args: [BytesLike, BytesLike],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  resolve(
    settlementPrice: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setDisableOrderRebate(
    disable: boolean,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setFundingHour(
    newFundingHour: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setLeverage(
    initialMarginRatio: BigNumberish,
    maintenanceMarginRatio: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setPlacePaused(
    paused: boolean,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setQuoteParam(
    param: QuoteParamStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  settle(
    expiry: BigNumberish,
    target: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  sweep(
    expiry: BigNumberish,
    target: string,
    size: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  trade(
    args: [BytesLike, BytesLike],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  tradeFor(
    to: string,
    args: [BytesLike, BytesLike],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  update(
    expiry: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    add(
      args: [BytesLike, BytesLike],
      overrides?: CallOverrides
    ): Promise<
      [number, number, RangeStructOutput] & {
        tickLower: number;
        tickUpper: number;
        range: RangeStructOutput;
      }
    >;

    addFor(
      to: string,
      args: [BytesLike, BytesLike],
      overrides?: CallOverrides
    ): Promise<
      [number, number, RangeStructOutput] & {
        tickLower: number;
        tickUpper: number;
        range: RangeStructOutput;
      }
    >;

    batchPlace(
      args: [BytesLike, BytesLike, BytesLike],
      overrides?: CallOverrides
    ): Promise<
      [number[], OrderStructOutput[]] & {
        nonces: number[];
        orders: OrderStructOutput[];
      }
    >;

    batchPlaceFor(
      to: string,
      args: [BytesLike, BytesLike, BytesLike],
      overrides?: CallOverrides
    ): Promise<
      [number[], OrderStructOutput[]] & {
        nonces: number[];
        orders: OrderStructOutput[];
      }
    >;

    cancel(
      arg: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [boolean[], PositionCacheStructOutput[]] & {
        succees: boolean[];
        pics: PositionCacheStructOutput[];
      }
    >;

    cancelFor(
      to: string,
      arg: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [boolean[], PositionCacheStructOutput[]] & {
        succees: boolean[];
        pics: PositionCacheStructOutput[];
      }
    >;

    claimProtocolFee(
      expiry: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    condition(overrides?: CallOverrides): Promise<number>;

    donateInsuranceFund(
      expiry: BigNumberish,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    fill(
      arg: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [PositionCacheStructOutput, BigNumber] & {
        pic: PositionCacheStructOutput;
        tip: BigNumber;
      }
    >;

    freeze(overrides?: CallOverrides): Promise<void>;

    getExpiries(overrides?: CallOverrides): Promise<number[]>;

    handler(overrides?: CallOverrides): Promise<string>;

    init(
      target: string,
      args: [BytesLike, BytesLike],
      overrides?: CallOverrides
    ): Promise<
      [number, number, RangeStructOutput] & {
        tickLower: number;
        tickUpper: number;
        range: RangeStructOutput;
      }
    >;

    initialize(data: BytesLike, overrides?: CallOverrides): Promise<void>;

    inquire(
      expiry: BigNumberish,
      size: BigNumberish,
      overrides?: CallOverrides
    ): Promise<QuotationStructOutput>;

    liquidate(
      expiry: BigNumberish,
      target: string,
      size: BigNumberish,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    multicall(data: BytesLike[], overrides?: CallOverrides): Promise<string[]>;

    normalize(overrides?: CallOverrides): Promise<void>;

    place(
      args: [BytesLike, BytesLike],
      overrides?: CallOverrides
    ): Promise<
      [number, OrderStructOutput] & { nonce: number; order: OrderStructOutput }
    >;

    placeFor(
      to: string,
      args: [BytesLike, BytesLike],
      overrides?: CallOverrides
    ): Promise<
      [number, OrderStructOutput] & { nonce: number; order: OrderStructOutput }
    >;

    queryAccount(
      expiry: BigNumberish,
      target: string,
      query: BigNumberish,
      inputs: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    queryContext(
      expiry: BigNumberish,
      query: BigNumberish,
      offsets: BigNumberish[],
      inputs: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    querySetting(
      offsets: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    recycleInsuranceFund(
      expiry: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    remove(
      args: [BytesLike, BytesLike],
      overrides?: CallOverrides
    ): Promise<
      [PositionCacheStructOutput, BigNumber, BigNumber] & {
        pic: PositionCacheStructOutput;
        fee: BigNumber;
        tip: BigNumber;
      }
    >;

    removeFor(
      args: [BytesLike, BytesLike],
      overrides?: CallOverrides
    ): Promise<
      [PositionCacheStructOutput, BigNumber, BigNumber] & {
        pic: PositionCacheStructOutput;
        fee: BigNumber;
        tip: BigNumber;
      }
    >;

    resolve(
      settlementPrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setDisableOrderRebate(
      disable: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setFundingHour(
      newFundingHour: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setLeverage(
      initialMarginRatio: BigNumberish,
      maintenanceMarginRatio: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setPlacePaused(paused: boolean, overrides?: CallOverrides): Promise<void>;

    setQuoteParam(
      param: QuoteParamStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    settle(
      expiry: BigNumberish,
      target: string,
      overrides?: CallOverrides
    ): Promise<void>;

    sweep(
      expiry: BigNumberish,
      target: string,
      size: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    trade(
      args: [BytesLike, BytesLike],
      overrides?: CallOverrides
    ): Promise<PositionCacheStructOutput>;

    tradeFor(
      to: string,
      args: [BytesLike, BytesLike],
      overrides?: CallOverrides
    ): Promise<PositionCacheStructOutput>;

    update(expiry: BigNumberish, overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "Add(uint32,address,int24,int24,(uint128,uint128,uint96,uint160))"(
      expiry?: BigNumberish | null,
      trader?: string | null,
      tickLower?: null,
      tickUpper?: null,
      range?: null
    ): AddEventFilter;
    Add(
      expiry?: BigNumberish | null,
      trader?: string | null,
      tickLower?: null,
      tickUpper?: null,
      range?: null
    ): AddEventFilter;

    "Adjust(uint32,address,int256)"(
      expiry?: BigNumberish | null,
      trader?: string | null,
      net?: null
    ): AdjustEventFilter;
    Adjust(
      expiry?: BigNumberish | null,
      trader?: string | null,
      net?: null
    ): AdjustEventFilter;

    "Cancel(uint32,address,int24,uint32,uint256,(int256,int256,uint256,uint256,int256))"(
      expiry?: BigNumberish | null,
      trader?: string | null,
      tick?: null,
      nonce?: null,
      fee?: null,
      pic?: null
    ): CancelEventFilter;
    Cancel(
      expiry?: BigNumberish | null,
      trader?: string | null,
      tick?: null,
      nonce?: null,
      fee?: null,
      pic?: null
    ): CancelEventFilter;

    "ClaimProtocolFee(uint32,uint256)"(
      expiry?: BigNumberish | null,
      amount?: null
    ): ClaimProtocolFeeEventFilter;
    ClaimProtocolFee(
      expiry?: BigNumberish | null,
      amount?: null
    ): ClaimProtocolFeeEventFilter;

    "DeleteContext(uint32)"(
      expiry?: BigNumberish | null
    ): DeleteContextEventFilter;
    DeleteContext(expiry?: BigNumberish | null): DeleteContextEventFilter;

    "DonateInsuranceFund(uint32,address,uint256)"(
      expiry?: BigNumberish | null,
      donator?: string | null,
      amount?: null
    ): DonateInsuranceFundEventFilter;
    DonateInsuranceFund(
      expiry?: BigNumberish | null,
      donator?: string | null,
      amount?: null
    ): DonateInsuranceFundEventFilter;

    "Fill(uint32,address,int24,uint32,uint256,(int256,int256,uint256,uint256,int256),address,uint256)"(
      expiry?: BigNumberish | null,
      trader?: string | null,
      tick?: null,
      nonce?: null,
      fee?: null,
      pic?: null,
      operator?: null,
      tip?: null
    ): FillEventFilter;
    Fill(
      expiry?: BigNumberish | null,
      trader?: string | null,
      tick?: null,
      nonce?: null,
      fee?: null,
      pic?: null,
      operator?: null,
      tip?: null
    ): FillEventFilter;

    "FundingFee(address,int256)"(
      trader?: string | null,
      funding?: null
    ): FundingFeeEventFilter;
    FundingFee(trader?: string | null, funding?: null): FundingFeeEventFilter;

    "Liquidate(uint32,address,uint256,uint256,address,int256)"(
      expiry?: BigNumberish | null,
      trader?: string | null,
      amount?: null,
      mark?: null,
      target?: null,
      size?: null
    ): LiquidateEventFilter;
    Liquidate(
      expiry?: BigNumberish | null,
      trader?: string | null,
      amount?: null,
      mark?: null,
      target?: null,
      size?: null
    ): LiquidateEventFilter;

    "Place(uint32,address,int24,uint32,(uint128,int128))"(
      expiry?: BigNumberish | null,
      trader?: string | null,
      tick?: null,
      nonce?: null,
      order?: null
    ): PlaceEventFilter;
    Place(
      expiry?: BigNumberish | null,
      trader?: string | null,
      tick?: null,
      nonce?: null,
      order?: null
    ): PlaceEventFilter;

    "RecycleInsuranceFund(uint32,uint256)"(
      expiry?: BigNumberish | null,
      amount?: null
    ): RecycleInsuranceFundEventFilter;
    RecycleInsuranceFund(
      expiry?: BigNumberish | null,
      amount?: null
    ): RecycleInsuranceFundEventFilter;

    "Remove(uint32,address,int24,int24,uint256,(int256,int256,uint256,uint256,int256),address,uint256)"(
      expiry?: BigNumberish | null,
      trader?: string | null,
      tickLower?: null,
      tickUpper?: null,
      fee?: null,
      pic?: null,
      operator?: null,
      tip?: null
    ): RemoveEventFilter;
    Remove(
      expiry?: BigNumberish | null,
      trader?: string | null,
      tickLower?: null,
      tickUpper?: null,
      fee?: null,
      pic?: null,
      operator?: null,
      tip?: null
    ): RemoveEventFilter;

    "Settle(uint32,address,uint256,uint256,address)"(
      expiry?: BigNumberish | null,
      trader?: string | null,
      settlement?: null,
      balance?: null,
      operator?: null
    ): SettleEventFilter;
    Settle(
      expiry?: BigNumberish | null,
      trader?: string | null,
      settlement?: null,
      balance?: null,
      operator?: null
    ): SettleEventFilter;

    "Sweep(uint32,address,int256,int256,uint256,uint256,uint16,uint160,uint256,address)"(
      expiry?: BigNumberish | null,
      trader?: string | null,
      size?: null,
      takenSize?: null,
      takenValue?: null,
      entryNotional?: null,
      feeRatio?: null,
      sqrtPX96?: null,
      mark?: null,
      operator?: null
    ): SweepEventFilter;
    Sweep(
      expiry?: BigNumberish | null,
      trader?: string | null,
      size?: null,
      takenSize?: null,
      takenValue?: null,
      entryNotional?: null,
      feeRatio?: null,
      sqrtPX96?: null,
      mark?: null,
      operator?: null
    ): SweepEventFilter;

    "Trade(uint32,address,int256,uint256,int256,uint256,uint256,uint16,uint160,uint256)"(
      expiry?: BigNumberish | null,
      trader?: string | null,
      size?: null,
      amount?: null,
      takenSize?: null,
      takenValue?: null,
      entryNotional?: null,
      feeRatio?: null,
      sqrtPX96?: null,
      mark?: null
    ): TradeEventFilter;
    Trade(
      expiry?: BigNumberish | null,
      trader?: string | null,
      size?: null,
      amount?: null,
      takenSize?: null,
      takenValue?: null,
      entryNotional?: null,
      feeRatio?: null,
      sqrtPX96?: null,
      mark?: null
    ): TradeEventFilter;

    "UpdateAmmStatus(uint32,uint8,uint160,uint256)"(
      expiry?: BigNumberish | null,
      status?: null,
      sqrtPX96?: null,
      mark?: null
    ): UpdateAmmStatusEventFilter;
    UpdateAmmStatus(
      expiry?: BigNumberish | null,
      status?: null,
      sqrtPX96?: null,
      mark?: null
    ): UpdateAmmStatusEventFilter;

    "UpdateCondition(uint32,uint8)"(
      timestamp?: null,
      condition?: null
    ): UpdateConditionEventFilter;
    UpdateCondition(
      timestamp?: null,
      condition?: null
    ): UpdateConditionEventFilter;

    "UpdateFeeState(uint32,uint128,uint128)"(
      expiry?: BigNumberish | null,
      feeIndex?: null,
      protocolFee?: null
    ): UpdateFeeStateEventFilter;
    UpdateFeeState(
      expiry?: BigNumberish | null,
      feeIndex?: null,
      protocolFee?: null
    ): UpdateFeeStateEventFilter;

    "UpdateFundingHour(uint8)"(
      fundingHour?: null
    ): UpdateFundingHourEventFilter;
    UpdateFundingHour(fundingHour?: null): UpdateFundingHourEventFilter;

    "UpdateFundingIndex(uint256)"(
      fundingIndex?: null
    ): UpdateFundingIndexEventFilter;
    UpdateFundingIndex(fundingIndex?: null): UpdateFundingIndexEventFilter;

    "UpdateMarginRatio(uint16,uint16)"(
      initialMarginRatio?: null,
      maintenanceMarginRatio?: null
    ): UpdateMarginRatioEventFilter;
    UpdateMarginRatio(
      initialMarginRatio?: null,
      maintenanceMarginRatio?: null
    ): UpdateMarginRatioEventFilter;

    "UpdateParam((uint128,uint16,uint16,uint8,uint128))"(
      param?: null
    ): UpdateParamEventFilter;
    UpdateParam(param?: null): UpdateParamEventFilter;

    "UpdatePosition(uint32,address,(int256,int256,uint256,uint256,int256))"(
      expiry?: BigNumberish | null,
      trader?: string | null,
      pic?: null
    ): UpdatePositionEventFilter;
    UpdatePosition(
      expiry?: BigNumberish | null,
      trader?: string | null,
      pic?: null
    ): UpdatePositionEventFilter;

    "UpdateSocialLossInsuranceFund(uint32,uint128,uint128,uint128)"(
      expiry?: BigNumberish | null,
      longSocialLossIndex?: null,
      shortSocialLossIndex?: null,
      insuranceFund?: null
    ): UpdateSocialLossInsuranceFundEventFilter;
    UpdateSocialLossInsuranceFund(
      expiry?: BigNumberish | null,
      longSocialLossIndex?: null,
      shortSocialLossIndex?: null,
      insuranceFund?: null
    ): UpdateSocialLossInsuranceFundEventFilter;

    "AdminChanged(address,address)"(
      previousAdmin?: null,
      newAdmin?: null
    ): AdminChangedEventFilter;
    AdminChanged(
      previousAdmin?: null,
      newAdmin?: null
    ): AdminChangedEventFilter;

    "BeaconUpgraded(address)"(
      beacon?: string | null
    ): BeaconUpgradedEventFilter;
    BeaconUpgraded(beacon?: string | null): BeaconUpgradedEventFilter;

    "Upgraded(address)"(implementation?: string | null): UpgradedEventFilter;
    Upgraded(implementation?: string | null): UpgradedEventFilter;
  };

  estimateGas: {
    add(
      args: [BytesLike, BytesLike],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    addFor(
      to: string,
      args: [BytesLike, BytesLike],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    batchPlace(
      args: [BytesLike, BytesLike, BytesLike],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    batchPlaceFor(
      to: string,
      args: [BytesLike, BytesLike, BytesLike],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    cancel(
      arg: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    cancelFor(
      to: string,
      arg: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    claimProtocolFee(
      expiry: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    condition(overrides?: CallOverrides): Promise<BigNumber>;

    donateInsuranceFund(
      expiry: BigNumberish,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    fill(
      arg: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    freeze(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    getExpiries(overrides?: CallOverrides): Promise<BigNumber>;

    handler(overrides?: CallOverrides): Promise<BigNumber>;

    init(
      target: string,
      args: [BytesLike, BytesLike],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    initialize(
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    inquire(
      expiry: BigNumberish,
      size: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    liquidate(
      expiry: BigNumberish,
      target: string,
      size: BigNumberish,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    multicall(
      data: BytesLike[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    normalize(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    place(
      args: [BytesLike, BytesLike],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    placeFor(
      to: string,
      args: [BytesLike, BytesLike],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    queryAccount(
      expiry: BigNumberish,
      target: string,
      query: BigNumberish,
      inputs: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    queryContext(
      expiry: BigNumberish,
      query: BigNumberish,
      offsets: BigNumberish[],
      inputs: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    querySetting(
      offsets: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    recycleInsuranceFund(
      expiry: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    remove(
      args: [BytesLike, BytesLike],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    removeFor(
      args: [BytesLike, BytesLike],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    resolve(
      settlementPrice: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setDisableOrderRebate(
      disable: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setFundingHour(
      newFundingHour: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setLeverage(
      initialMarginRatio: BigNumberish,
      maintenanceMarginRatio: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setPlacePaused(
      paused: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setQuoteParam(
      param: QuoteParamStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    settle(
      expiry: BigNumberish,
      target: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    sweep(
      expiry: BigNumberish,
      target: string,
      size: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    trade(
      args: [BytesLike, BytesLike],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    tradeFor(
      to: string,
      args: [BytesLike, BytesLike],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    update(
      expiry: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    add(
      args: [BytesLike, BytesLike],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    addFor(
      to: string,
      args: [BytesLike, BytesLike],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    batchPlace(
      args: [BytesLike, BytesLike, BytesLike],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    batchPlaceFor(
      to: string,
      args: [BytesLike, BytesLike, BytesLike],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    cancel(
      arg: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    cancelFor(
      to: string,
      arg: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    claimProtocolFee(
      expiry: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    condition(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    donateInsuranceFund(
      expiry: BigNumberish,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    fill(
      arg: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    freeze(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getExpiries(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    handler(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    init(
      target: string,
      args: [BytesLike, BytesLike],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    initialize(
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    inquire(
      expiry: BigNumberish,
      size: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    liquidate(
      expiry: BigNumberish,
      target: string,
      size: BigNumberish,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    multicall(
      data: BytesLike[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    normalize(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    place(
      args: [BytesLike, BytesLike],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    placeFor(
      to: string,
      args: [BytesLike, BytesLike],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    queryAccount(
      expiry: BigNumberish,
      target: string,
      query: BigNumberish,
      inputs: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    queryContext(
      expiry: BigNumberish,
      query: BigNumberish,
      offsets: BigNumberish[],
      inputs: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    querySetting(
      offsets: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    recycleInsuranceFund(
      expiry: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    remove(
      args: [BytesLike, BytesLike],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    removeFor(
      args: [BytesLike, BytesLike],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    resolve(
      settlementPrice: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setDisableOrderRebate(
      disable: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setFundingHour(
      newFundingHour: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setLeverage(
      initialMarginRatio: BigNumberish,
      maintenanceMarginRatio: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setPlacePaused(
      paused: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setQuoteParam(
      param: QuoteParamStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    settle(
      expiry: BigNumberish,
      target: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    sweep(
      expiry: BigNumberish,
      target: string,
      size: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    trade(
      args: [BytesLike, BytesLike],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    tradeFor(
      to: string,
      args: [BytesLike, BytesLike],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    update(
      expiry: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
