/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export type PositionStruct = {
  balance: BigNumberish;
  size: BigNumberish;
  entryNotional: BigNumberish;
  entrySocialLossIndex: BigNumberish;
  entryFundingIndex: BigNumberish;
};

export type PositionStructOutput = [
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber
] & {
  balance: BigNumber;
  size: BigNumber;
  entryNotional: BigNumber;
  entrySocialLossIndex: BigNumber;
  entryFundingIndex: BigNumber;
};

export type OrderStruct = { balance: BigNumberish; size: BigNumberish };

export type OrderStructOutput = [BigNumber, BigNumber] & {
  balance: BigNumber;
  size: BigNumber;
};

export type RangeStruct = {
  liquidity: BigNumberish;
  entryFeeIndex: BigNumberish;
  balance: BigNumberish;
  sqrtEntryPX96: BigNumberish;
};

export type RangeStructOutput = [BigNumber, BigNumber, BigNumber, BigNumber] & {
  liquidity: BigNumber;
  entryFeeIndex: BigNumber;
  balance: BigNumber;
  sqrtEntryPX96: BigNumber;
};

export type PortfolioStruct = {
  oids: BigNumberish[];
  rids: BigNumberish[];
  position: PositionStruct;
  orders: OrderStruct[];
  ranges: RangeStruct[];
  ordersTaken: BigNumberish[];
};

export type PortfolioStructOutput = [
  number[],
  number[],
  PositionStructOutput,
  OrderStructOutput[],
  RangeStructOutput[],
  BigNumber[]
] & {
  oids: number[];
  rids: number[];
  position: PositionStructOutput;
  orders: OrderStructOutput[];
  ranges: RangeStructOutput[];
  ordersTaken: BigNumber[];
};

export type BlockInfoStruct = { timestamp: BigNumberish; height: BigNumberish };

export type BlockInfoStructOutput = [number, number] & {
  timestamp: number;
  height: number;
};

export type QuoteParamStruct = {
  minMarginAmount: BigNumberish;
  tradingFeeRatio: BigNumberish;
  protocolFeeRatio: BigNumberish;
  qtype: BigNumberish;
  tip: BigNumberish;
};

export type QuoteParamStructOutput = [
  BigNumber,
  number,
  number,
  number,
  BigNumber
] & {
  minMarginAmount: BigNumber;
  tradingFeeRatio: number;
  protocolFeeRatio: number;
  qtype: number;
  tip: BigNumber;
};

export type SettingStruct = {
  symbol: string;
  config: string;
  gate: string;
  market: string;
  quote: string;
  decimals: BigNumberish;
  initialMarginRatio: BigNumberish;
  maintenanceMarginRatio: BigNumberish;
  placePaused: boolean;
  fundingHour: BigNumberish;
  disableOrderRebate: boolean;
  param: QuoteParamStruct;
};

export type SettingStructOutput = [
  string,
  string,
  string,
  string,
  string,
  number,
  number,
  number,
  boolean,
  number,
  boolean,
  QuoteParamStructOutput
] & {
  symbol: string;
  config: string;
  gate: string;
  market: string;
  quote: string;
  decimals: number;
  initialMarginRatio: number;
  maintenanceMarginRatio: number;
  placePaused: boolean;
  fundingHour: number;
  disableOrderRebate: boolean;
  param: QuoteParamStructOutput;
};

export type DexV2FeederStruct = {
  ftype: BigNumberish;
  isToken0Quote: boolean;
  pair: string;
  scaler0: BigNumberish;
  scaler1: BigNumberish;
};

export type DexV2FeederStructOutput = [
  number,
  boolean,
  string,
  BigNumber,
  BigNumber
] & {
  ftype: number;
  isToken0Quote: boolean;
  pair: string;
  scaler0: BigNumber;
  scaler1: BigNumber;
};

export type PriceFeederStruct = {
  ftype: BigNumberish;
  scaler0: BigNumberish;
  aggregator0: string;
  heartBeat0: BigNumberish;
  scaler1: BigNumberish;
  aggregator1: string;
  heartBeat1: BigNumberish;
};

export type PriceFeederStructOutput = [
  number,
  BigNumber,
  string,
  number,
  BigNumber,
  string,
  number
] & {
  ftype: number;
  scaler0: BigNumber;
  aggregator0: string;
  heartBeat0: number;
  scaler1: BigNumber;
  aggregator1: string;
  heartBeat1: number;
};

export type AmmStruct = {
  expiry: BigNumberish;
  timestamp: BigNumberish;
  status: BigNumberish;
  tick: BigNumberish;
  sqrtPX96: BigNumberish;
  liquidity: BigNumberish;
  totalLiquidity: BigNumberish;
  totalShort: BigNumberish;
  openInterests: BigNumberish;
  totalLong: BigNumberish;
  involvedFund: BigNumberish;
  feeIndex: BigNumberish;
  protocolFee: BigNumberish;
  longSocialLossIndex: BigNumberish;
  shortSocialLossIndex: BigNumberish;
  longFundingIndex: BigNumberish;
  shortFundingIndex: BigNumberish;
  insuranceFund: BigNumberish;
  settlementPrice: BigNumberish;
};

export type AmmStructOutput = [
  number,
  number,
  number,
  number,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber
] & {
  expiry: number;
  timestamp: number;
  status: number;
  tick: number;
  sqrtPX96: BigNumber;
  liquidity: BigNumber;
  totalLiquidity: BigNumber;
  totalShort: BigNumber;
  openInterests: BigNumber;
  totalLong: BigNumber;
  involvedFund: BigNumber;
  feeIndex: BigNumber;
  protocolFee: BigNumber;
  longSocialLossIndex: BigNumber;
  shortSocialLossIndex: BigNumber;
  longFundingIndex: BigNumber;
  shortFundingIndex: BigNumber;
  insuranceFund: BigNumber;
  settlementPrice: BigNumber;
};

export type AssembledInstrumentDataStruct = {
  instrumentAddr: string;
  handler: string;
  setting: SettingStruct;
  dexV2Feeder: DexV2FeederStruct;
  priceFeeder: PriceFeederStruct;
  spotPrice: BigNumberish;
  condition: BigNumberish;
  amms: AmmStruct[];
  markPrices: BigNumberish[];
};

export type AssembledInstrumentDataStructOutput = [
  string,
  string,
  SettingStructOutput,
  DexV2FeederStructOutput,
  PriceFeederStructOutput,
  BigNumber,
  number,
  AmmStructOutput[],
  BigNumber[]
] & {
  instrumentAddr: string;
  handler: string;
  setting: SettingStructOutput;
  dexV2Feeder: DexV2FeederStructOutput;
  priceFeeder: PriceFeederStructOutput;
  spotPrice: BigNumber;
  condition: number;
  amms: AmmStructOutput[];
  markPrices: BigNumber[];
};

export type FetchInstrumentParamStruct = {
  instrument: string;
  expiries: BigNumberish[];
};

export type FetchInstrumentParamStructOutput = [string, number[]] & {
  instrument: string;
  expiries: number[];
};

export type PearlStruct = {
  liquidityGross: BigNumberish;
  liquidityNet: BigNumberish;
  nonce: BigNumberish;
  left: BigNumberish;
  taken: BigNumberish;
  fee: BigNumberish;
  entrySocialLossIndex: BigNumberish;
  entryFundingIndex: BigNumberish;
};

export type PearlStructOutput = [
  BigNumber,
  BigNumber,
  number,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber
] & {
  liquidityGross: BigNumber;
  liquidityNet: BigNumber;
  nonce: number;
  left: BigNumber;
  taken: BigNumber;
  fee: BigNumber;
  entrySocialLossIndex: BigNumber;
  entryFundingIndex: BigNumber;
};

export type PendingStruct = {
  timestamp: BigNumberish;
  native: boolean;
  amount: BigNumberish;
  exemption: BigNumberish;
};

export type PendingStructOutput = [number, boolean, BigNumber, BigNumber] & {
  timestamp: number;
  native: boolean;
  amount: BigNumber;
  exemption: BigNumber;
};

export type RecordStruct = {
  taken: BigNumberish;
  fee: BigNumberish;
  entrySocialLossIndex: BigNumberish;
  entryFundingIndex: BigNumberish;
};

export type RecordStructOutput = [
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber
] & {
  taken: BigNumber;
  fee: BigNumber;
  entrySocialLossIndex: BigNumber;
  entryFundingIndex: BigNumber;
};

export type QuotationStruct = {
  benchmark: BigNumberish;
  sqrtFairPX96: BigNumberish;
  tick: BigNumberish;
  mark: BigNumberish;
  entryNotional: BigNumberish;
  fee: BigNumberish;
  minAmount: BigNumberish;
  sqrtPostFairPX96: BigNumberish;
  postTick: BigNumberish;
};

export type QuotationStructOutput = [
  BigNumber,
  BigNumber,
  number,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  number
] & {
  benchmark: BigNumber;
  sqrtFairPX96: BigNumber;
  tick: number;
  mark: BigNumber;
  entryNotional: BigNumber;
  fee: BigNumber;
  minAmount: BigNumber;
  sqrtPostFairPX96: BigNumber;
  postTick: number;
};

export type CurveStateStruct = {
  sqrtPX96: BigNumberish;
  tick: BigNumberish;
  liquidity: BigNumberish;
};

export type CurveStateStructOutput = [BigNumber, number, BigNumber] & {
  sqrtPX96: BigNumber;
  tick: number;
  liquidity: BigNumber;
};

export type MinimalPearlStruct = {
  liquidityNet: BigNumberish;
  left: BigNumberish;
};

export type MinimalPearlStructOutput = [BigNumber, BigNumber] & {
  liquidityNet: BigNumber;
  left: BigNumber;
};

export interface ObserverInterface extends utils.Interface {
  functions: {
    "gate()": FunctionFragment;
    "getAcc(address,uint32,address)": FunctionFragment;
    "getAccMeta(address,uint32,address)": FunctionFragment;
    "getAllInstruments()": FunctionFragment;
    "getAmm(address,uint32)": FunctionFragment;
    "getInstrumentBatch((address,uint32[])[])": FunctionFragment;
    "getInstrumentByAddressList(address[])": FunctionFragment;
    "getNextInitializedTickOutside(address,uint32,int24,bool)": FunctionFragment;
    "getOrderIndexes(address,uint32,address)": FunctionFragment;
    "getOrders(address,uint32,address,uint48[])": FunctionFragment;
    "getPearls(address,uint32,int24[])": FunctionFragment;
    "getPendings(address[],address)": FunctionFragment;
    "getPortfolios(address,address)": FunctionFragment;
    "getPosition(address,uint32,address)": FunctionFragment;
    "getQuoteParam(address)": FunctionFragment;
    "getRangeIndexes(address,uint32,address)": FunctionFragment;
    "getRanges(address,uint32,address,uint48[])": FunctionFragment;
    "getRecords(address,uint32,int24[],uint24[])": FunctionFragment;
    "getSetting(address)": FunctionFragment;
    "getTickBitmaps(address,uint32,int16[])": FunctionFragment;
    "getVaultBalances(address,address[])": FunctionFragment;
    "inquireByNotional(address,uint32,uint256,bool)": FunctionFragment;
    "inquireByTick(address,uint32,int24)": FunctionFragment;
    "inspectMaxReserveDexV2Pair(address,address)": FunctionFragment;
    "liquidityDetails(address,uint32,uint24)": FunctionFragment;
    "sizeByNotional(address,uint32,uint256,bool)": FunctionFragment;
    "sizeToTick(address,uint32,int24)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "gate"
      | "getAcc"
      | "getAccMeta"
      | "getAllInstruments"
      | "getAmm"
      | "getInstrumentBatch"
      | "getInstrumentByAddressList"
      | "getNextInitializedTickOutside"
      | "getOrderIndexes"
      | "getOrders"
      | "getPearls"
      | "getPendings"
      | "getPortfolios"
      | "getPosition"
      | "getQuoteParam"
      | "getRangeIndexes"
      | "getRanges"
      | "getRecords"
      | "getSetting"
      | "getTickBitmaps"
      | "getVaultBalances"
      | "inquireByNotional"
      | "inquireByTick"
      | "inspectMaxReserveDexV2Pair"
      | "liquidityDetails"
      | "sizeByNotional"
      | "sizeToTick"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "gate", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAcc",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccMeta",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllInstruments",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAmm",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getInstrumentBatch",
    values: [FetchInstrumentParamStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getInstrumentByAddressList",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getNextInitializedTickOutside",
    values: [string, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrderIndexes",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrders",
    values: [string, BigNumberish, string, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getPearls",
    values: [string, BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendings",
    values: [string[], string]
  ): string;
  encodeFunctionData(
    functionFragment: "getPortfolios",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getPosition",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getQuoteParam",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getRangeIndexes",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getRanges",
    values: [string, BigNumberish, string, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecords",
    values: [string, BigNumberish, BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(functionFragment: "getSetting", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getTickBitmaps",
    values: [string, BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultBalances",
    values: [string, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "inquireByNotional",
    values: [string, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "inquireByTick",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "inspectMaxReserveDexV2Pair",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidityDetails",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sizeByNotional",
    values: [string, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "sizeToTick",
    values: [string, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "gate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAcc", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAccMeta", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllInstruments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAmm", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getInstrumentBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInstrumentByAddressList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNextInitializedTickOutside",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOrderIndexes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOrders", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPearls", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPendings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPortfolios",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getQuoteParam",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRangeIndexes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRanges", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getRecords", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getSetting", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTickBitmaps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVaultBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "inquireByNotional",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "inquireByTick",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "inspectMaxReserveDexV2Pair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidityDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sizeByNotional",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sizeToTick", data: BytesLike): Result;

  events: {};
}

export interface Observer extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ObserverInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    gate(overrides?: CallOverrides): Promise<[string]>;

    getAcc(
      instrument: string,
      expiry: BigNumberish,
      target: string,
      overrides?: CallOverrides
    ): Promise<
      [PortfolioStructOutput, BlockInfoStructOutput] & {
        portfolio: PortfolioStructOutput;
        blockInfo: BlockInfoStructOutput;
      }
    >;

    getAccMeta(
      instrument: string,
      expiry: BigNumberish,
      target: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { onumber: BigNumber; rnumber: BigNumber }
    >;

    getAllInstruments(
      overrides?: CallOverrides
    ): Promise<[AssembledInstrumentDataStructOutput[], BlockInfoStructOutput]>;

    getAmm(
      instrument: string,
      expiry: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[AmmStructOutput]>;

    getInstrumentBatch(
      params: FetchInstrumentParamStruct[],
      overrides?: CallOverrides
    ): Promise<[AssembledInstrumentDataStructOutput[], BlockInfoStructOutput]>;

    getInstrumentByAddressList(
      instrumentList: string[],
      overrides?: CallOverrides
    ): Promise<[AssembledInstrumentDataStructOutput[], BlockInfoStructOutput]>;

    getNextInitializedTickOutside(
      instrument: string,
      expiry: BigNumberish,
      tick: BigNumberish,
      right: boolean,
      overrides?: CallOverrides
    ): Promise<[number]>;

    getOrderIndexes(
      instrument: string,
      expiry: BigNumberish,
      target: string,
      overrides?: CallOverrides
    ): Promise<[number[]]>;

    getOrders(
      instrument: string,
      expiry: BigNumberish,
      target: string,
      oids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<[OrderStructOutput[]]>;

    getPearls(
      instrument: string,
      expiry: BigNumberish,
      tids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<[PearlStructOutput[]]>;

    getPendings(
      quotes: string[],
      trader: string,
      overrides?: CallOverrides
    ): Promise<
      [PendingStructOutput[], BlockInfoStructOutput] & {
        pendings: PendingStructOutput[];
        blockInfo: BlockInfoStructOutput;
      }
    >;

    getPortfolios(
      target: string,
      instrument: string,
      overrides?: CallOverrides
    ): Promise<
      [number[], PortfolioStructOutput[], BlockInfoStructOutput] & {
        expiries: number[];
        portfolios: PortfolioStructOutput[];
        blockInfo: BlockInfoStructOutput;
      }
    >;

    getPosition(
      instrument: string,
      expiry: BigNumberish,
      target: string,
      overrides?: CallOverrides
    ): Promise<[PositionStructOutput]>;

    getQuoteParam(
      instrument: string,
      overrides?: CallOverrides
    ): Promise<[QuoteParamStructOutput]>;

    getRangeIndexes(
      instrument: string,
      expiry: BigNumberish,
      target: string,
      overrides?: CallOverrides
    ): Promise<[number[]]>;

    getRanges(
      instrument: string,
      expiry: BigNumberish,
      target: string,
      rids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<[RangeStructOutput[]]>;

    getRecords(
      instrument: string,
      expiry: BigNumberish,
      tids: BigNumberish[],
      nonces: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<[RecordStructOutput[]]>;

    getSetting(
      instrument: string,
      overrides?: CallOverrides
    ): Promise<[SettingStructOutput]>;

    getTickBitmaps(
      instrument: string,
      expiry: BigNumberish,
      tbids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    getVaultBalances(
      target: string,
      quotes: string[],
      overrides?: CallOverrides
    ): Promise<[BigNumber[], BlockInfoStructOutput]>;

    inquireByNotional(
      instrument: string,
      expiry: BigNumberish,
      notional: BigNumberish,
      long: boolean,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, QuotationStructOutput] & {
        size: BigNumber;
        quotation: QuotationStructOutput;
      }
    >;

    inquireByTick(
      instrument: string,
      expiry: BigNumberish,
      tick: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, QuotationStructOutput] & {
        size: BigNumber;
        quotation: QuotationStructOutput;
      }
    >;

    inspectMaxReserveDexV2Pair(
      base: string,
      quote: string,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        maxReservePair: string;
        reserve0: BigNumber;
        reserve1: BigNumber;
      }
    >;

    liquidityDetails(
      instrument: string,
      expiry: BigNumberish,
      tickDelta: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        CurveStateStructOutput,
        number[],
        MinimalPearlStructOutput[],
        BlockInfoStructOutput
      ] & {
        amm: CurveStateStructOutput;
        tids: number[];
        pearls: MinimalPearlStructOutput[];
        blockInfo: BlockInfoStructOutput;
      }
    >;

    sizeByNotional(
      instrument: string,
      expiry: BigNumberish,
      notional: BigNumberish,
      long: boolean,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    sizeToTick(
      instrument: string,
      expiry: BigNumberish,
      destTick: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  gate(overrides?: CallOverrides): Promise<string>;

  getAcc(
    instrument: string,
    expiry: BigNumberish,
    target: string,
    overrides?: CallOverrides
  ): Promise<
    [PortfolioStructOutput, BlockInfoStructOutput] & {
      portfolio: PortfolioStructOutput;
      blockInfo: BlockInfoStructOutput;
    }
  >;

  getAccMeta(
    instrument: string,
    expiry: BigNumberish,
    target: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { onumber: BigNumber; rnumber: BigNumber }
  >;

  getAllInstruments(
    overrides?: CallOverrides
  ): Promise<[AssembledInstrumentDataStructOutput[], BlockInfoStructOutput]>;

  getAmm(
    instrument: string,
    expiry: BigNumberish,
    overrides?: CallOverrides
  ): Promise<AmmStructOutput>;

  getInstrumentBatch(
    params: FetchInstrumentParamStruct[],
    overrides?: CallOverrides
  ): Promise<[AssembledInstrumentDataStructOutput[], BlockInfoStructOutput]>;

  getInstrumentByAddressList(
    instrumentList: string[],
    overrides?: CallOverrides
  ): Promise<[AssembledInstrumentDataStructOutput[], BlockInfoStructOutput]>;

  getNextInitializedTickOutside(
    instrument: string,
    expiry: BigNumberish,
    tick: BigNumberish,
    right: boolean,
    overrides?: CallOverrides
  ): Promise<number>;

  getOrderIndexes(
    instrument: string,
    expiry: BigNumberish,
    target: string,
    overrides?: CallOverrides
  ): Promise<number[]>;

  getOrders(
    instrument: string,
    expiry: BigNumberish,
    target: string,
    oids: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<OrderStructOutput[]>;

  getPearls(
    instrument: string,
    expiry: BigNumberish,
    tids: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<PearlStructOutput[]>;

  getPendings(
    quotes: string[],
    trader: string,
    overrides?: CallOverrides
  ): Promise<
    [PendingStructOutput[], BlockInfoStructOutput] & {
      pendings: PendingStructOutput[];
      blockInfo: BlockInfoStructOutput;
    }
  >;

  getPortfolios(
    target: string,
    instrument: string,
    overrides?: CallOverrides
  ): Promise<
    [number[], PortfolioStructOutput[], BlockInfoStructOutput] & {
      expiries: number[];
      portfolios: PortfolioStructOutput[];
      blockInfo: BlockInfoStructOutput;
    }
  >;

  getPosition(
    instrument: string,
    expiry: BigNumberish,
    target: string,
    overrides?: CallOverrides
  ): Promise<PositionStructOutput>;

  getQuoteParam(
    instrument: string,
    overrides?: CallOverrides
  ): Promise<QuoteParamStructOutput>;

  getRangeIndexes(
    instrument: string,
    expiry: BigNumberish,
    target: string,
    overrides?: CallOverrides
  ): Promise<number[]>;

  getRanges(
    instrument: string,
    expiry: BigNumberish,
    target: string,
    rids: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<RangeStructOutput[]>;

  getRecords(
    instrument: string,
    expiry: BigNumberish,
    tids: BigNumberish[],
    nonces: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<RecordStructOutput[]>;

  getSetting(
    instrument: string,
    overrides?: CallOverrides
  ): Promise<SettingStructOutput>;

  getTickBitmaps(
    instrument: string,
    expiry: BigNumberish,
    tbids: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  getVaultBalances(
    target: string,
    quotes: string[],
    overrides?: CallOverrides
  ): Promise<[BigNumber[], BlockInfoStructOutput]>;

  inquireByNotional(
    instrument: string,
    expiry: BigNumberish,
    notional: BigNumberish,
    long: boolean,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, QuotationStructOutput] & {
      size: BigNumber;
      quotation: QuotationStructOutput;
    }
  >;

  inquireByTick(
    instrument: string,
    expiry: BigNumberish,
    tick: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, QuotationStructOutput] & {
      size: BigNumber;
      quotation: QuotationStructOutput;
    }
  >;

  inspectMaxReserveDexV2Pair(
    base: string,
    quote: string,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber] & {
      maxReservePair: string;
      reserve0: BigNumber;
      reserve1: BigNumber;
    }
  >;

  liquidityDetails(
    instrument: string,
    expiry: BigNumberish,
    tickDelta: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      CurveStateStructOutput,
      number[],
      MinimalPearlStructOutput[],
      BlockInfoStructOutput
    ] & {
      amm: CurveStateStructOutput;
      tids: number[];
      pearls: MinimalPearlStructOutput[];
      blockInfo: BlockInfoStructOutput;
    }
  >;

  sizeByNotional(
    instrument: string,
    expiry: BigNumberish,
    notional: BigNumberish,
    long: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  sizeToTick(
    instrument: string,
    expiry: BigNumberish,
    destTick: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    gate(overrides?: CallOverrides): Promise<string>;

    getAcc(
      instrument: string,
      expiry: BigNumberish,
      target: string,
      overrides?: CallOverrides
    ): Promise<
      [PortfolioStructOutput, BlockInfoStructOutput] & {
        portfolio: PortfolioStructOutput;
        blockInfo: BlockInfoStructOutput;
      }
    >;

    getAccMeta(
      instrument: string,
      expiry: BigNumberish,
      target: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { onumber: BigNumber; rnumber: BigNumber }
    >;

    getAllInstruments(
      overrides?: CallOverrides
    ): Promise<[AssembledInstrumentDataStructOutput[], BlockInfoStructOutput]>;

    getAmm(
      instrument: string,
      expiry: BigNumberish,
      overrides?: CallOverrides
    ): Promise<AmmStructOutput>;

    getInstrumentBatch(
      params: FetchInstrumentParamStruct[],
      overrides?: CallOverrides
    ): Promise<[AssembledInstrumentDataStructOutput[], BlockInfoStructOutput]>;

    getInstrumentByAddressList(
      instrumentList: string[],
      overrides?: CallOverrides
    ): Promise<[AssembledInstrumentDataStructOutput[], BlockInfoStructOutput]>;

    getNextInitializedTickOutside(
      instrument: string,
      expiry: BigNumberish,
      tick: BigNumberish,
      right: boolean,
      overrides?: CallOverrides
    ): Promise<number>;

    getOrderIndexes(
      instrument: string,
      expiry: BigNumberish,
      target: string,
      overrides?: CallOverrides
    ): Promise<number[]>;

    getOrders(
      instrument: string,
      expiry: BigNumberish,
      target: string,
      oids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<OrderStructOutput[]>;

    getPearls(
      instrument: string,
      expiry: BigNumberish,
      tids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PearlStructOutput[]>;

    getPendings(
      quotes: string[],
      trader: string,
      overrides?: CallOverrides
    ): Promise<
      [PendingStructOutput[], BlockInfoStructOutput] & {
        pendings: PendingStructOutput[];
        blockInfo: BlockInfoStructOutput;
      }
    >;

    getPortfolios(
      target: string,
      instrument: string,
      overrides?: CallOverrides
    ): Promise<
      [number[], PortfolioStructOutput[], BlockInfoStructOutput] & {
        expiries: number[];
        portfolios: PortfolioStructOutput[];
        blockInfo: BlockInfoStructOutput;
      }
    >;

    getPosition(
      instrument: string,
      expiry: BigNumberish,
      target: string,
      overrides?: CallOverrides
    ): Promise<PositionStructOutput>;

    getQuoteParam(
      instrument: string,
      overrides?: CallOverrides
    ): Promise<QuoteParamStructOutput>;

    getRangeIndexes(
      instrument: string,
      expiry: BigNumberish,
      target: string,
      overrides?: CallOverrides
    ): Promise<number[]>;

    getRanges(
      instrument: string,
      expiry: BigNumberish,
      target: string,
      rids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<RangeStructOutput[]>;

    getRecords(
      instrument: string,
      expiry: BigNumberish,
      tids: BigNumberish[],
      nonces: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<RecordStructOutput[]>;

    getSetting(
      instrument: string,
      overrides?: CallOverrides
    ): Promise<SettingStructOutput>;

    getTickBitmaps(
      instrument: string,
      expiry: BigNumberish,
      tbids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    getVaultBalances(
      target: string,
      quotes: string[],
      overrides?: CallOverrides
    ): Promise<[BigNumber[], BlockInfoStructOutput]>;

    inquireByNotional(
      instrument: string,
      expiry: BigNumberish,
      notional: BigNumberish,
      long: boolean,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, QuotationStructOutput] & {
        size: BigNumber;
        quotation: QuotationStructOutput;
      }
    >;

    inquireByTick(
      instrument: string,
      expiry: BigNumberish,
      tick: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, QuotationStructOutput] & {
        size: BigNumber;
        quotation: QuotationStructOutput;
      }
    >;

    inspectMaxReserveDexV2Pair(
      base: string,
      quote: string,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        maxReservePair: string;
        reserve0: BigNumber;
        reserve1: BigNumber;
      }
    >;

    liquidityDetails(
      instrument: string,
      expiry: BigNumberish,
      tickDelta: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        CurveStateStructOutput,
        number[],
        MinimalPearlStructOutput[],
        BlockInfoStructOutput
      ] & {
        amm: CurveStateStructOutput;
        tids: number[];
        pearls: MinimalPearlStructOutput[];
        blockInfo: BlockInfoStructOutput;
      }
    >;

    sizeByNotional(
      instrument: string,
      expiry: BigNumberish,
      notional: BigNumberish,
      long: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sizeToTick(
      instrument: string,
      expiry: BigNumberish,
      destTick: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    gate(overrides?: CallOverrides): Promise<BigNumber>;

    getAcc(
      instrument: string,
      expiry: BigNumberish,
      target: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAccMeta(
      instrument: string,
      expiry: BigNumberish,
      target: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAllInstruments(overrides?: CallOverrides): Promise<BigNumber>;

    getAmm(
      instrument: string,
      expiry: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getInstrumentBatch(
      params: FetchInstrumentParamStruct[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getInstrumentByAddressList(
      instrumentList: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getNextInitializedTickOutside(
      instrument: string,
      expiry: BigNumberish,
      tick: BigNumberish,
      right: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getOrderIndexes(
      instrument: string,
      expiry: BigNumberish,
      target: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getOrders(
      instrument: string,
      expiry: BigNumberish,
      target: string,
      oids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPearls(
      instrument: string,
      expiry: BigNumberish,
      tids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPendings(
      quotes: string[],
      trader: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPortfolios(
      target: string,
      instrument: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPosition(
      instrument: string,
      expiry: BigNumberish,
      target: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getQuoteParam(
      instrument: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRangeIndexes(
      instrument: string,
      expiry: BigNumberish,
      target: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRanges(
      instrument: string,
      expiry: BigNumberish,
      target: string,
      rids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRecords(
      instrument: string,
      expiry: BigNumberish,
      tids: BigNumberish[],
      nonces: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSetting(
      instrument: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTickBitmaps(
      instrument: string,
      expiry: BigNumberish,
      tbids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getVaultBalances(
      target: string,
      quotes: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    inquireByNotional(
      instrument: string,
      expiry: BigNumberish,
      notional: BigNumberish,
      long: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    inquireByTick(
      instrument: string,
      expiry: BigNumberish,
      tick: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    inspectMaxReserveDexV2Pair(
      base: string,
      quote: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    liquidityDetails(
      instrument: string,
      expiry: BigNumberish,
      tickDelta: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sizeByNotional(
      instrument: string,
      expiry: BigNumberish,
      notional: BigNumberish,
      long: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sizeToTick(
      instrument: string,
      expiry: BigNumberish,
      destTick: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    gate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getAcc(
      instrument: string,
      expiry: BigNumberish,
      target: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAccMeta(
      instrument: string,
      expiry: BigNumberish,
      target: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAllInstruments(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getAmm(
      instrument: string,
      expiry: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getInstrumentBatch(
      params: FetchInstrumentParamStruct[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getInstrumentByAddressList(
      instrumentList: string[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getNextInitializedTickOutside(
      instrument: string,
      expiry: BigNumberish,
      tick: BigNumberish,
      right: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getOrderIndexes(
      instrument: string,
      expiry: BigNumberish,
      target: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getOrders(
      instrument: string,
      expiry: BigNumberish,
      target: string,
      oids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPearls(
      instrument: string,
      expiry: BigNumberish,
      tids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPendings(
      quotes: string[],
      trader: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPortfolios(
      target: string,
      instrument: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPosition(
      instrument: string,
      expiry: BigNumberish,
      target: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getQuoteParam(
      instrument: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRangeIndexes(
      instrument: string,
      expiry: BigNumberish,
      target: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRanges(
      instrument: string,
      expiry: BigNumberish,
      target: string,
      rids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRecords(
      instrument: string,
      expiry: BigNumberish,
      tids: BigNumberish[],
      nonces: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSetting(
      instrument: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTickBitmaps(
      instrument: string,
      expiry: BigNumberish,
      tbids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getVaultBalances(
      target: string,
      quotes: string[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    inquireByNotional(
      instrument: string,
      expiry: BigNumberish,
      notional: BigNumberish,
      long: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    inquireByTick(
      instrument: string,
      expiry: BigNumberish,
      tick: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    inspectMaxReserveDexV2Pair(
      base: string,
      quote: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    liquidityDetails(
      instrument: string,
      expiry: BigNumberish,
      tickDelta: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    sizeByNotional(
      instrument: string,
      expiry: BigNumberish,
      notional: BigNumberish,
      long: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    sizeToTick(
      instrument: string,
      expiry: BigNumberish,
      destTick: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
