/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
    BaseContract,
    BigNumber,
    BigNumberish,
    BytesLike,
    CallOverrides,
    ContractTransaction,
    Overrides,
    PopulatedTransaction,
    Signer,
    utils,
} from 'ethers';
import type { FunctionFragment, Result, EventFragment } from '@ethersproject/abi';
import type { Listener, Provider } from '@ethersproject/providers';
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from './common';

export interface StorkFeederFactoryInterface extends utils.Interface {
    functions: {
        'DEFAULT_ADMIN_ROLE()': FunctionFragment;
        'OPERATOR_ROLE()': FunctionFragment;
        'allFeeders(uint256)': FunctionFragment;
        'baseIndexToFeeder(bytes32)': FunctionFragment;
        'batchCreateFeeder(bytes32[],bytes32[])': FunctionFragment;
        'batchGetPrice(bytes32[])': FunctionFragment;
        'beacon()': FunctionFragment;
        'createFeeder(bytes32,bytes32)': FunctionFragment;
        'feederToBaseIndex(address)': FunctionFragment;
        'getAllFeeders()': FunctionFragment;
        'getAllFeedersLength()': FunctionFragment;
        'getAllIndexes()': FunctionFragment;
        'getPrice(bytes32)': FunctionFragment;
        'getRoleAdmin(bytes32)': FunctionFragment;
        'grantRole(bytes32,address)': FunctionFragment;
        'hasRole(bytes32,address)': FunctionFragment;
        'initialize(address,address[])': FunctionFragment;
        'renounceRole(bytes32,address)': FunctionFragment;
        'revokeRole(bytes32,address)': FunctionFragment;
        'setFeederId(bytes32,bytes32)': FunctionFragment;
        'stork()': FunctionFragment;
        'supportsInterface(bytes4)': FunctionFragment;
    };

    getFunction(
        nameOrSignatureOrTopic:
            | 'DEFAULT_ADMIN_ROLE'
            | 'OPERATOR_ROLE'
            | 'allFeeders'
            | 'baseIndexToFeeder'
            | 'batchCreateFeeder'
            | 'batchGetPrice'
            | 'beacon'
            | 'createFeeder'
            | 'feederToBaseIndex'
            | 'getAllFeeders'
            | 'getAllFeedersLength'
            | 'getAllIndexes'
            | 'getPrice'
            | 'getRoleAdmin'
            | 'grantRole'
            | 'hasRole'
            | 'initialize'
            | 'renounceRole'
            | 'revokeRole'
            | 'setFeederId'
            | 'stork'
            | 'supportsInterface',
    ): FunctionFragment;

    encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
    encodeFunctionData(functionFragment: 'OPERATOR_ROLE', values?: undefined): string;
    encodeFunctionData(functionFragment: 'allFeeders', values: [BigNumberish]): string;
    encodeFunctionData(functionFragment: 'baseIndexToFeeder', values: [BytesLike]): string;
    encodeFunctionData(functionFragment: 'batchCreateFeeder', values: [BytesLike[], BytesLike[]]): string;
    encodeFunctionData(functionFragment: 'batchGetPrice', values: [BytesLike[]]): string;
    encodeFunctionData(functionFragment: 'beacon', values?: undefined): string;
    encodeFunctionData(functionFragment: 'createFeeder', values: [BytesLike, BytesLike]): string;
    encodeFunctionData(functionFragment: 'feederToBaseIndex', values: [string]): string;
    encodeFunctionData(functionFragment: 'getAllFeeders', values?: undefined): string;
    encodeFunctionData(functionFragment: 'getAllFeedersLength', values?: undefined): string;
    encodeFunctionData(functionFragment: 'getAllIndexes', values?: undefined): string;
    encodeFunctionData(functionFragment: 'getPrice', values: [BytesLike]): string;
    encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
    encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, string]): string;
    encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, string]): string;
    encodeFunctionData(functionFragment: 'initialize', values: [string, string[]]): string;
    encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, string]): string;
    encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, string]): string;
    encodeFunctionData(functionFragment: 'setFeederId', values: [BytesLike, BytesLike]): string;
    encodeFunctionData(functionFragment: 'stork', values?: undefined): string;
    encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
    decodeFunctionResult(functionFragment: 'OPERATOR_ROLE', data: BytesLike): Result;
    decodeFunctionResult(functionFragment: 'allFeeders', data: BytesLike): Result;
    decodeFunctionResult(functionFragment: 'baseIndexToFeeder', data: BytesLike): Result;
    decodeFunctionResult(functionFragment: 'batchCreateFeeder', data: BytesLike): Result;
    decodeFunctionResult(functionFragment: 'batchGetPrice', data: BytesLike): Result;
    decodeFunctionResult(functionFragment: 'beacon', data: BytesLike): Result;
    decodeFunctionResult(functionFragment: 'createFeeder', data: BytesLike): Result;
    decodeFunctionResult(functionFragment: 'feederToBaseIndex', data: BytesLike): Result;
    decodeFunctionResult(functionFragment: 'getAllFeeders', data: BytesLike): Result;
    decodeFunctionResult(functionFragment: 'getAllFeedersLength', data: BytesLike): Result;
    decodeFunctionResult(functionFragment: 'getAllIndexes', data: BytesLike): Result;
    decodeFunctionResult(functionFragment: 'getPrice', data: BytesLike): Result;
    decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
    decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
    decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
    decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
    decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
    decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
    decodeFunctionResult(functionFragment: 'setFeederId', data: BytesLike): Result;
    decodeFunctionResult(functionFragment: 'stork', data: BytesLike): Result;
    decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;

    events: {
        'FeederCreated(address,bytes32)': EventFragment;
        'Initialized(uint8)': EventFragment;
        'RoleAdminChanged(bytes32,bytes32,bytes32)': EventFragment;
        'RoleGranted(bytes32,address,address)': EventFragment;
        'RoleRevoked(bytes32,address,address)': EventFragment;
        'SetFeederId(bytes32,bytes32)': EventFragment;
    };

    getEvent(nameOrSignatureOrTopic: 'FeederCreated'): EventFragment;
    getEvent(nameOrSignatureOrTopic: 'Initialized'): EventFragment;
    getEvent(nameOrSignatureOrTopic: 'RoleAdminChanged'): EventFragment;
    getEvent(nameOrSignatureOrTopic: 'RoleGranted'): EventFragment;
    getEvent(nameOrSignatureOrTopic: 'RoleRevoked'): EventFragment;
    getEvent(nameOrSignatureOrTopic: 'SetFeederId'): EventFragment;
}

export interface FeederCreatedEventObject {
    feeder: string;
    symbolHash: string;
}
export type FeederCreatedEvent = TypedEvent<[string, string], FeederCreatedEventObject>;

export type FeederCreatedEventFilter = TypedEventFilter<FeederCreatedEvent>;

export interface InitializedEventObject {
    version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface RoleAdminChangedEventObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
}
export type RoleAdminChangedEvent = TypedEvent<[string, string, string], RoleAdminChangedEventObject>;

export type RoleAdminChangedEventFilter = TypedEventFilter<RoleAdminChangedEvent>;

export interface RoleGrantedEventObject {
    role: string;
    account: string;
    sender: string;
}
export type RoleGrantedEvent = TypedEvent<[string, string, string], RoleGrantedEventObject>;

export type RoleGrantedEventFilter = TypedEventFilter<RoleGrantedEvent>;

export interface RoleRevokedEventObject {
    role: string;
    account: string;
    sender: string;
}
export type RoleRevokedEvent = TypedEvent<[string, string, string], RoleRevokedEventObject>;

export type RoleRevokedEventFilter = TypedEventFilter<RoleRevokedEvent>;

export interface SetFeederIdEventObject {
    baseIndex: string;
    feederId: string;
}
export type SetFeederIdEvent = TypedEvent<[string, string], SetFeederIdEventObject>;

export type SetFeederIdEventFilter = TypedEventFilter<SetFeederIdEvent>;

export interface StorkFeederFactory extends BaseContract {
    connect(signerOrProvider: Signer | Provider | string): this;
    attach(addressOrName: string): this;
    deployed(): Promise<this>;

    interface: StorkFeederFactoryInterface;

    queryFilter<TEvent extends TypedEvent>(
        event: TypedEventFilter<TEvent>,
        fromBlockOrBlockhash?: string | number | undefined,
        toBlock?: string | number | undefined,
    ): Promise<Array<TEvent>>;

    listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>;
    listeners(eventName?: string): Array<Listener>;
    removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
    removeAllListeners(eventName?: string): this;
    off: OnEvent<this>;
    on: OnEvent<this>;
    once: OnEvent<this>;
    removeListener: OnEvent<this>;

    functions: {
        DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

        OPERATOR_ROLE(overrides?: CallOverrides): Promise<[string]>;

        allFeeders(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

        baseIndexToFeeder(baseIndex: BytesLike, overrides?: CallOverrides): Promise<[string] & { feeder: string }>;

        batchCreateFeeder(
            baseIndexes: BytesLike[],
            feederIds: BytesLike[],
            overrides?: Overrides & { from?: string },
        ): Promise<ContractTransaction>;

        batchGetPrice(
            baseIndexes: BytesLike[],
            overrides?: CallOverrides,
        ): Promise<[BigNumber[], number[]] & { prices: BigNumber[]; timestamps: number[] }>;

        beacon(overrides?: CallOverrides): Promise<[string]>;

        createFeeder(
            baseIndex: BytesLike,
            feederId: BytesLike,
            overrides?: Overrides & { from?: string },
        ): Promise<ContractTransaction>;

        feederToBaseIndex(feeder: string, overrides?: CallOverrides): Promise<[string] & { baseIndex: string }>;

        getAllFeeders(overrides?: CallOverrides): Promise<[string[]]>;

        getAllFeedersLength(overrides?: CallOverrides): Promise<[BigNumber]>;

        getAllIndexes(overrides?: CallOverrides): Promise<[string[]]>;

        getPrice(
            baseIndex: BytesLike,
            overrides?: CallOverrides,
        ): Promise<[BigNumber, number] & { price: BigNumber; timestamp: number }>;

        getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<[string]>;

        grantRole(
            role: BytesLike,
            account: string,
            overrides?: Overrides & { from?: string },
        ): Promise<ContractTransaction>;

        hasRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<[boolean]>;

        initialize(
            admin: string,
            operators: string[],
            overrides?: Overrides & { from?: string },
        ): Promise<ContractTransaction>;

        renounceRole(
            role: BytesLike,
            account: string,
            overrides?: Overrides & { from?: string },
        ): Promise<ContractTransaction>;

        revokeRole(
            role: BytesLike,
            account: string,
            overrides?: Overrides & { from?: string },
        ): Promise<ContractTransaction>;

        setFeederId(
            baseIndex: BytesLike,
            feederId: BytesLike,
            overrides?: Overrides & { from?: string },
        ): Promise<ContractTransaction>;

        stork(overrides?: CallOverrides): Promise<[string]>;

        supportsInterface(interfaceId: BytesLike, overrides?: CallOverrides): Promise<[boolean]>;
    };

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    OPERATOR_ROLE(overrides?: CallOverrides): Promise<string>;

    allFeeders(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    baseIndexToFeeder(baseIndex: BytesLike, overrides?: CallOverrides): Promise<string>;

    batchCreateFeeder(
        baseIndexes: BytesLike[],
        feederIds: BytesLike[],
        overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    batchGetPrice(
        baseIndexes: BytesLike[],
        overrides?: CallOverrides,
    ): Promise<[BigNumber[], number[]] & { prices: BigNumber[]; timestamps: number[] }>;

    beacon(overrides?: CallOverrides): Promise<string>;

    createFeeder(
        baseIndex: BytesLike,
        feederId: BytesLike,
        overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    feederToBaseIndex(feeder: string, overrides?: CallOverrides): Promise<string>;

    getAllFeeders(overrides?: CallOverrides): Promise<string[]>;

    getAllFeedersLength(overrides?: CallOverrides): Promise<BigNumber>;

    getAllIndexes(overrides?: CallOverrides): Promise<string[]>;

    getPrice(
        baseIndex: BytesLike,
        overrides?: CallOverrides,
    ): Promise<[BigNumber, number] & { price: BigNumber; timestamp: number }>;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

    grantRole(
        role: BytesLike,
        account: string,
        overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    hasRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<boolean>;

    initialize(
        admin: string,
        operators: string[],
        overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    renounceRole(
        role: BytesLike,
        account: string,
        overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    revokeRole(
        role: BytesLike,
        account: string,
        overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    setFeederId(
        baseIndex: BytesLike,
        feederId: BytesLike,
        overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    stork(overrides?: CallOverrides): Promise<string>;

    supportsInterface(interfaceId: BytesLike, overrides?: CallOverrides): Promise<boolean>;

    callStatic: {
        DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

        OPERATOR_ROLE(overrides?: CallOverrides): Promise<string>;

        allFeeders(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

        baseIndexToFeeder(baseIndex: BytesLike, overrides?: CallOverrides): Promise<string>;

        batchCreateFeeder(
            baseIndexes: BytesLike[],
            feederIds: BytesLike[],
            overrides?: CallOverrides,
        ): Promise<string[]>;

        batchGetPrice(
            baseIndexes: BytesLike[],
            overrides?: CallOverrides,
        ): Promise<[BigNumber[], number[]] & { prices: BigNumber[]; timestamps: number[] }>;

        beacon(overrides?: CallOverrides): Promise<string>;

        createFeeder(baseIndex: BytesLike, feederId: BytesLike, overrides?: CallOverrides): Promise<string>;

        feederToBaseIndex(feeder: string, overrides?: CallOverrides): Promise<string>;

        getAllFeeders(overrides?: CallOverrides): Promise<string[]>;

        getAllFeedersLength(overrides?: CallOverrides): Promise<BigNumber>;

        getAllIndexes(overrides?: CallOverrides): Promise<string[]>;

        getPrice(
            baseIndex: BytesLike,
            overrides?: CallOverrides,
        ): Promise<[BigNumber, number] & { price: BigNumber; timestamp: number }>;

        getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

        grantRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<void>;

        hasRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<boolean>;

        initialize(admin: string, operators: string[], overrides?: CallOverrides): Promise<void>;

        renounceRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<void>;

        revokeRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<void>;

        setFeederId(baseIndex: BytesLike, feederId: BytesLike, overrides?: CallOverrides): Promise<void>;

        stork(overrides?: CallOverrides): Promise<string>;

        supportsInterface(interfaceId: BytesLike, overrides?: CallOverrides): Promise<boolean>;
    };

    filters: {
        'FeederCreated(address,bytes32)'(feeder?: string | null, symbolHash?: null): FeederCreatedEventFilter;
        FeederCreated(feeder?: string | null, symbolHash?: null): FeederCreatedEventFilter;

        'Initialized(uint8)'(version?: null): InitializedEventFilter;
        Initialized(version?: null): InitializedEventFilter;

        'RoleAdminChanged(bytes32,bytes32,bytes32)'(
            role?: BytesLike | null,
            previousAdminRole?: BytesLike | null,
            newAdminRole?: BytesLike | null,
        ): RoleAdminChangedEventFilter;
        RoleAdminChanged(
            role?: BytesLike | null,
            previousAdminRole?: BytesLike | null,
            newAdminRole?: BytesLike | null,
        ): RoleAdminChangedEventFilter;

        'RoleGranted(bytes32,address,address)'(
            role?: BytesLike | null,
            account?: string | null,
            sender?: string | null,
        ): RoleGrantedEventFilter;
        RoleGranted(role?: BytesLike | null, account?: string | null, sender?: string | null): RoleGrantedEventFilter;

        'RoleRevoked(bytes32,address,address)'(
            role?: BytesLike | null,
            account?: string | null,
            sender?: string | null,
        ): RoleRevokedEventFilter;
        RoleRevoked(role?: BytesLike | null, account?: string | null, sender?: string | null): RoleRevokedEventFilter;

        'SetFeederId(bytes32,bytes32)'(baseIndex?: BytesLike | null, feederId?: null): SetFeederIdEventFilter;
        SetFeederId(baseIndex?: BytesLike | null, feederId?: null): SetFeederIdEventFilter;
    };

    estimateGas: {
        DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

        OPERATOR_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

        allFeeders(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

        baseIndexToFeeder(baseIndex: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

        batchCreateFeeder(
            baseIndexes: BytesLike[],
            feederIds: BytesLike[],
            overrides?: Overrides & { from?: string },
        ): Promise<BigNumber>;

        batchGetPrice(baseIndexes: BytesLike[], overrides?: CallOverrides): Promise<BigNumber>;

        beacon(overrides?: CallOverrides): Promise<BigNumber>;

        createFeeder(
            baseIndex: BytesLike,
            feederId: BytesLike,
            overrides?: Overrides & { from?: string },
        ): Promise<BigNumber>;

        feederToBaseIndex(feeder: string, overrides?: CallOverrides): Promise<BigNumber>;

        getAllFeeders(overrides?: CallOverrides): Promise<BigNumber>;

        getAllFeedersLength(overrides?: CallOverrides): Promise<BigNumber>;

        getAllIndexes(overrides?: CallOverrides): Promise<BigNumber>;

        getPrice(baseIndex: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

        getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

        grantRole(role: BytesLike, account: string, overrides?: Overrides & { from?: string }): Promise<BigNumber>;

        hasRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<BigNumber>;

        initialize(admin: string, operators: string[], overrides?: Overrides & { from?: string }): Promise<BigNumber>;

        renounceRole(role: BytesLike, account: string, overrides?: Overrides & { from?: string }): Promise<BigNumber>;

        revokeRole(role: BytesLike, account: string, overrides?: Overrides & { from?: string }): Promise<BigNumber>;

        setFeederId(
            baseIndex: BytesLike,
            feederId: BytesLike,
            overrides?: Overrides & { from?: string },
        ): Promise<BigNumber>;

        stork(overrides?: CallOverrides): Promise<BigNumber>;

        supportsInterface(interfaceId: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;
    };

    populateTransaction: {
        DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

        OPERATOR_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

        allFeeders(arg0: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>;

        baseIndexToFeeder(baseIndex: BytesLike, overrides?: CallOverrides): Promise<PopulatedTransaction>;

        batchCreateFeeder(
            baseIndexes: BytesLike[],
            feederIds: BytesLike[],
            overrides?: Overrides & { from?: string },
        ): Promise<PopulatedTransaction>;

        batchGetPrice(baseIndexes: BytesLike[], overrides?: CallOverrides): Promise<PopulatedTransaction>;

        beacon(overrides?: CallOverrides): Promise<PopulatedTransaction>;

        createFeeder(
            baseIndex: BytesLike,
            feederId: BytesLike,
            overrides?: Overrides & { from?: string },
        ): Promise<PopulatedTransaction>;

        feederToBaseIndex(feeder: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

        getAllFeeders(overrides?: CallOverrides): Promise<PopulatedTransaction>;

        getAllFeedersLength(overrides?: CallOverrides): Promise<PopulatedTransaction>;

        getAllIndexes(overrides?: CallOverrides): Promise<PopulatedTransaction>;

        getPrice(baseIndex: BytesLike, overrides?: CallOverrides): Promise<PopulatedTransaction>;

        getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<PopulatedTransaction>;

        grantRole(
            role: BytesLike,
            account: string,
            overrides?: Overrides & { from?: string },
        ): Promise<PopulatedTransaction>;

        hasRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

        initialize(
            admin: string,
            operators: string[],
            overrides?: Overrides & { from?: string },
        ): Promise<PopulatedTransaction>;

        renounceRole(
            role: BytesLike,
            account: string,
            overrides?: Overrides & { from?: string },
        ): Promise<PopulatedTransaction>;

        revokeRole(
            role: BytesLike,
            account: string,
            overrides?: Overrides & { from?: string },
        ): Promise<PopulatedTransaction>;

        setFeederId(
            baseIndex: BytesLike,
            feederId: BytesLike,
            overrides?: Overrides & { from?: string },
        ): Promise<PopulatedTransaction>;

        stork(overrides?: CallOverrides): Promise<PopulatedTransaction>;

        supportsInterface(interfaceId: BytesLike, overrides?: CallOverrides): Promise<PopulatedTransaction>;
    };
}
